// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_account

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func AccountDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cust_address": schema.StringAttribute{
				Computed:            true,
				Description:         "Postal address.",
				MarkdownDescription: "Postal address.",
			},
			"cust_billing_email": schema.StringAttribute{
				Computed:            true,
				Description:         "Billing email.",
				MarkdownDescription: "Billing email.",
			},
			"cust_city": schema.StringAttribute{
				Computed:            true,
				Description:         "City.",
				MarkdownDescription: "City.",
			},
			"cust_company_no": schema.StringAttribute{
				Computed:            true,
				Description:         "Organization/company number.",
				MarkdownDescription: "Organization/company number.",
			},
			"cust_country": schema.StringAttribute{
				Computed:            true,
				Description:         "Country.",
				MarkdownDescription: "Country.",
			},
			"cust_email": schema.StringAttribute{
				Computed:            true,
				Description:         "Primary contact email.",
				MarkdownDescription: "Primary contact email.",
			},
			"cust_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Customer id.",
				MarkdownDescription: "Customer id.",
			},
			"cust_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Customer (company or person) name.",
				MarkdownDescription: "Customer (company or person) name.",
			},
			"cust_phone": schema.StringAttribute{
				Computed:            true,
				Description:         "Phone number.",
				MarkdownDescription: "Phone number.",
			},
			"cust_zipcode": schema.StringAttribute{
				Computed:            true,
				Description:         "Postal/ZIP code.",
				MarkdownDescription: "Postal/ZIP code.",
			},
		},
	}
}

type AccountModel struct {
	CustAddress      types.String `tfsdk:"cust_address"`
	CustBillingEmail types.String `tfsdk:"cust_billing_email"`
	CustCity         types.String `tfsdk:"cust_city"`
	CustCompanyNo    types.String `tfsdk:"cust_company_no"`
	CustCountry      types.String `tfsdk:"cust_country"`
	CustEmail        types.String `tfsdk:"cust_email"`
	CustId           types.String `tfsdk:"cust_id"`
	CustName         types.String `tfsdk:"cust_name"`
	CustPhone        types.String `tfsdk:"cust_phone"`
	CustZipcode      types.String `tfsdk:"cust_zipcode"`
}
