// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_dns_record

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func DnsRecordResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"record_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Record id.",
				MarkdownDescription: "Record id.",
			},
			"record_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Record name (host); defaults to \"@\".",
				MarkdownDescription: "Record name (host); defaults to \"@\".",
				Default:             stringdefault.StaticString("@"),
			},
			"record_priority": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Priority (used by MX and SRV records).",
				MarkdownDescription: "Priority (used by MX and SRV records).",
			},
			"record_ttl": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Time to live, in seconds; defaults to 3600.",
				MarkdownDescription: "Time to live, in seconds; defaults to 3600.",
				Default:             int64default.StaticInt64(3600),
			},
			"record_type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Record type; defaults to \"A\".",
				MarkdownDescription: "Record type; defaults to \"A\".",
				Default:             stringdefault.StaticString("A"),
			},
			"record_value": schema.StringAttribute{
				Required:            true,
				Description:         "Record value (content).",
				MarkdownDescription: "Record value (content).",
			},
			"zone_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type DnsRecordModel struct {
	RecordId       types.String `tfsdk:"record_id"`
	RecordName     types.String `tfsdk:"record_name"`
	RecordPriority types.Int64  `tfsdk:"record_priority"`
	RecordTtl      types.Int64  `tfsdk:"record_ttl"`
	RecordType     types.String `tfsdk:"record_type"`
	RecordValue    types.String `tfsdk:"record_value"`
	ZoneId         types.String `tfsdk:"zone_id"`
}
