// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_ssh_key

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SshKeyResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"key_added": schema.StringAttribute{
				Computed:            true,
				Description:         "When the key was added (Unix timestamp, string-encoded).",
				MarkdownDescription: "When the key was added (Unix timestamp, string-encoded).",
			},
			"key_data": schema.StringAttribute{
				Required:            true,
				Description:         "The OpenSSH public key material.",
				MarkdownDescription: "The OpenSSH public key material.",
			},
			"key_id": schema.StringAttribute{
				Computed:            true,
				Description:         "SSH key id.",
				MarkdownDescription: "SSH key id.",
			},
			"key_name": schema.StringAttribute{
				Required:            true,
				Description:         "Label for the SSH key.",
				MarkdownDescription: "Label for the SSH key.",
			},
		},
	}
}

type SshKeyModel struct {
	KeyAdded types.String `tfsdk:"key_added"`
	KeyData  types.String `tfsdk:"key_data"`
	KeyId    types.String `tfsdk:"key_id"`
	KeyName  types.String `tfsdk:"key_name"`
}
