// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_ssh_keys

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SshKeysDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ssh_keys": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"key_added": schema.StringAttribute{
							Computed:            true,
							Description:         "When the key was added (Unix timestamp, string-encoded).",
							MarkdownDescription: "When the key was added (Unix timestamp, string-encoded).",
						},
						"key_data": schema.StringAttribute{
							Computed:            true,
							Description:         "The OpenSSH public key material.",
							MarkdownDescription: "The OpenSSH public key material.",
						},
						"key_id": schema.StringAttribute{
							Computed:            true,
							Description:         "SSH key id.",
							MarkdownDescription: "SSH key id.",
						},
						"key_name": schema.StringAttribute{
							Computed:            true,
							Description:         "SSH key name.",
							MarkdownDescription: "SSH key name.",
						},
					},
					CustomType: SshKeysType{
						ObjectType: types.ObjectType{
							AttrTypes: SshKeysValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "SSH public keys registered on the account.",
				MarkdownDescription: "SSH public keys registered on the account.",
			},
		},
	}
}

type SshKeysModel struct {
	SshKeys types.List `tfsdk:"ssh_keys"`
}

var _ basetypes.ObjectTypable = SshKeysType{}

type SshKeysType struct {
	basetypes.ObjectType
}

func (t SshKeysType) Equal(o attr.Type) bool {
	other, ok := o.(SshKeysType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SshKeysType) String() string {
	return "SshKeysType"
}

func (t SshKeysType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	keyAddedAttribute, ok := attributes["key_added"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key_added is missing from object`)

		return nil, diags
	}

	keyAddedVal, ok := keyAddedAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key_added expected to be basetypes.StringValue, was: %T`, keyAddedAttribute))
	}

	keyDataAttribute, ok := attributes["key_data"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key_data is missing from object`)

		return nil, diags
	}

	keyDataVal, ok := keyDataAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key_data expected to be basetypes.StringValue, was: %T`, keyDataAttribute))
	}

	keyIdAttribute, ok := attributes["key_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key_id is missing from object`)

		return nil, diags
	}

	keyIdVal, ok := keyIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key_id expected to be basetypes.StringValue, was: %T`, keyIdAttribute))
	}

	keyNameAttribute, ok := attributes["key_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key_name is missing from object`)

		return nil, diags
	}

	keyNameVal, ok := keyNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key_name expected to be basetypes.StringValue, was: %T`, keyNameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return SshKeysValue{
		KeyAdded: keyAddedVal,
		KeyData:  keyDataVal,
		KeyId:    keyIdVal,
		KeyName:  keyNameVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewSshKeysValueNull() SshKeysValue {
	return SshKeysValue{
		state: attr.ValueStateNull,
	}
}

func NewSshKeysValueUnknown() SshKeysValue {
	return SshKeysValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSshKeysValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SshKeysValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SshKeysValue Attribute Value",
				"While creating a SshKeysValue value, a missing attribute value was detected. "+
					"A SshKeysValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SshKeysValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SshKeysValue Attribute Type",
				"While creating a SshKeysValue value, an invalid attribute value was detected. "+
					"A SshKeysValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SshKeysValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SshKeysValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SshKeysValue Attribute Value",
				"While creating a SshKeysValue value, an extra attribute value was detected. "+
					"A SshKeysValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SshKeysValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSshKeysValueUnknown(), diags
	}

	keyAddedAttribute, ok := attributes["key_added"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key_added is missing from object`)

		return NewSshKeysValueUnknown(), diags
	}

	keyAddedVal, ok := keyAddedAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key_added expected to be basetypes.StringValue, was: %T`, keyAddedAttribute))
	}

	keyDataAttribute, ok := attributes["key_data"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key_data is missing from object`)

		return NewSshKeysValueUnknown(), diags
	}

	keyDataVal, ok := keyDataAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key_data expected to be basetypes.StringValue, was: %T`, keyDataAttribute))
	}

	keyIdAttribute, ok := attributes["key_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key_id is missing from object`)

		return NewSshKeysValueUnknown(), diags
	}

	keyIdVal, ok := keyIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key_id expected to be basetypes.StringValue, was: %T`, keyIdAttribute))
	}

	keyNameAttribute, ok := attributes["key_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key_name is missing from object`)

		return NewSshKeysValueUnknown(), diags
	}

	keyNameVal, ok := keyNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key_name expected to be basetypes.StringValue, was: %T`, keyNameAttribute))
	}

	if diags.HasError() {
		return NewSshKeysValueUnknown(), diags
	}

	return SshKeysValue{
		KeyAdded: keyAddedVal,
		KeyData:  keyDataVal,
		KeyId:    keyIdVal,
		KeyName:  keyNameVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewSshKeysValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SshKeysValue {
	object, diags := NewSshKeysValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewSshKeysValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SshKeysType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSshKeysValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSshKeysValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSshKeysValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSshKeysValueMust(SshKeysValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SshKeysType) ValueType(ctx context.Context) attr.Value {
	return SshKeysValue{}
}

var _ basetypes.ObjectValuable = SshKeysValue{}

type SshKeysValue struct {
	KeyAdded basetypes.StringValue `tfsdk:"key_added"`
	KeyData  basetypes.StringValue `tfsdk:"key_data"`
	KeyId    basetypes.StringValue `tfsdk:"key_id"`
	KeyName  basetypes.StringValue `tfsdk:"key_name"`
	state    attr.ValueState
}

func (v SshKeysValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["key_added"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["key_data"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["key_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["key_name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.KeyAdded.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key_added"] = val

		val, err = v.KeyData.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key_data"] = val

		val, err = v.KeyId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key_id"] = val

		val, err = v.KeyName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key_name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SshKeysValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SshKeysValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SshKeysValue) String() string {
	return "SshKeysValue"
}

func (v SshKeysValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"key_added": basetypes.StringType{},
		"key_data":  basetypes.StringType{},
		"key_id":    basetypes.StringType{},
		"key_name":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"key_added": v.KeyAdded,
			"key_data":  v.KeyData,
			"key_id":    v.KeyId,
			"key_name":  v.KeyName,
		})

	return objVal, diags
}

func (v SshKeysValue) Equal(o attr.Value) bool {
	other, ok := o.(SshKeysValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.KeyAdded.Equal(other.KeyAdded) {
		return false
	}

	if !v.KeyData.Equal(other.KeyData) {
		return false
	}

	if !v.KeyId.Equal(other.KeyId) {
		return false
	}

	if !v.KeyName.Equal(other.KeyName) {
		return false
	}

	return true
}

func (v SshKeysValue) Type(ctx context.Context) attr.Type {
	return SshKeysType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SshKeysValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"key_added": basetypes.StringType{},
		"key_data":  basetypes.StringType{},
		"key_id":    basetypes.StringType{},
		"key_name":  basetypes.StringType{},
	}
}
