// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_dns_redirect

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func DnsRedirectResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"enabled": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether the redirect is active.",
				MarkdownDescription: "Whether the redirect is active.",
			},
			"source": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Subdomain the redirect applies to; defaults to \"@\" (the zone root).",
				MarkdownDescription: "Subdomain the redirect applies to; defaults to \"@\" (the zone root).",
				Default:             stringdefault.StaticString("@"),
			},
			"target_url": schema.StringAttribute{
				Required:            true,
				Description:         "URL that requests are redirected to.",
				MarkdownDescription: "URL that requests are redirected to.",
			},
			"zone_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type DnsRedirectModel struct {
	Enabled   types.Bool   `tfsdk:"enabled"`
	Source    types.String `tfsdk:"source"`
	TargetUrl types.String `tfsdk:"target_url"`
	ZoneId    types.String `tfsdk:"zone_id"`
}
