provider:
  name: gigahost

data_sources:
  account:
    read:
      path: /account
      method: GET
    schema:
      ignores:
        - ssh_keys

  ssh_keys:
    read:
      path: /account
      method: GET
    schema:
      ignores:
        - cust_id
        - cust_name
        - cust_address
        - cust_zipcode
        - cust_city
        - cust_country
        - cust_phone
        - cust_email
        - cust_company_no
        - cust_billing_email

  dns_zones:
    read:
      path: /dns/zones
      method: GET

  dns_records:
    read:
      path: /dns/zones/{zone_id}/records
      method: GET

  server_catalog:
    read:
      path: /deploy/servers
      method: GET

  servers:
    read:
      path: /servers
      method: GET
