// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_dns_records

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func DnsRecordsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"records": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"record_id": schema.StringAttribute{
							Computed:            true,
							Description:         "Record id.",
							MarkdownDescription: "Record id.",
						},
						"record_name": schema.StringAttribute{
							Computed:            true,
							Description:         "Record name (host), e.g. \"@\" or \"www\".",
							MarkdownDescription: "Record name (host), e.g. \"@\" or \"www\".",
						},
						"record_priority": schema.Int64Attribute{
							Computed:            true,
							Description:         "Priority (used by MX and SRV records).",
							MarkdownDescription: "Priority (used by MX and SRV records).",
						},
						"record_ttl": schema.Int64Attribute{
							Computed:            true,
							Description:         "Time to live, in seconds.",
							MarkdownDescription: "Time to live, in seconds.",
						},
						"record_type": schema.StringAttribute{
							Computed:            true,
							Description:         "Record type (A, AAAA, CNAME, MX, TXT, NS, etc.).",
							MarkdownDescription: "Record type (A, AAAA, CNAME, MX, TXT, NS, etc.).",
						},
						"record_value": schema.StringAttribute{
							Computed:            true,
							Description:         "Record value (content).",
							MarkdownDescription: "Record value (content).",
						},
					},
					CustomType: RecordsType{
						ObjectType: types.ObjectType{
							AttrTypes: RecordsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "DNS records in the zone.",
				MarkdownDescription: "DNS records in the zone.",
			},
			"zone_id": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type DnsRecordsModel struct {
	Records types.List   `tfsdk:"records"`
	ZoneId  types.String `tfsdk:"zone_id"`
}

var _ basetypes.ObjectTypable = RecordsType{}

type RecordsType struct {
	basetypes.ObjectType
}

func (t RecordsType) Equal(o attr.Type) bool {
	other, ok := o.(RecordsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t RecordsType) String() string {
	return "RecordsType"
}

func (t RecordsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	recordIdAttribute, ok := attributes["record_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`record_id is missing from object`)

		return nil, diags
	}

	recordIdVal, ok := recordIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`record_id expected to be basetypes.StringValue, was: %T`, recordIdAttribute))
	}

	recordNameAttribute, ok := attributes["record_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`record_name is missing from object`)

		return nil, diags
	}

	recordNameVal, ok := recordNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`record_name expected to be basetypes.StringValue, was: %T`, recordNameAttribute))
	}

	recordPriorityAttribute, ok := attributes["record_priority"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`record_priority is missing from object`)

		return nil, diags
	}

	recordPriorityVal, ok := recordPriorityAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`record_priority expected to be basetypes.Int64Value, was: %T`, recordPriorityAttribute))
	}

	recordTtlAttribute, ok := attributes["record_ttl"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`record_ttl is missing from object`)

		return nil, diags
	}

	recordTtlVal, ok := recordTtlAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`record_ttl expected to be basetypes.Int64Value, was: %T`, recordTtlAttribute))
	}

	recordTypeAttribute, ok := attributes["record_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`record_type is missing from object`)

		return nil, diags
	}

	recordTypeVal, ok := recordTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`record_type expected to be basetypes.StringValue, was: %T`, recordTypeAttribute))
	}

	recordValueAttribute, ok := attributes["record_value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`record_value is missing from object`)

		return nil, diags
	}

	recordValueVal, ok := recordValueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`record_value expected to be basetypes.StringValue, was: %T`, recordValueAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return RecordsValue{
		RecordId:       recordIdVal,
		RecordName:     recordNameVal,
		RecordPriority: recordPriorityVal,
		RecordTtl:      recordTtlVal,
		RecordType:     recordTypeVal,
		RecordValue:    recordValueVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewRecordsValueNull() RecordsValue {
	return RecordsValue{
		state: attr.ValueStateNull,
	}
}

func NewRecordsValueUnknown() RecordsValue {
	return RecordsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewRecordsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (RecordsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing RecordsValue Attribute Value",
				"While creating a RecordsValue value, a missing attribute value was detected. "+
					"A RecordsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RecordsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid RecordsValue Attribute Type",
				"While creating a RecordsValue value, an invalid attribute value was detected. "+
					"A RecordsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RecordsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("RecordsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra RecordsValue Attribute Value",
				"While creating a RecordsValue value, an extra attribute value was detected. "+
					"A RecordsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra RecordsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewRecordsValueUnknown(), diags
	}

	recordIdAttribute, ok := attributes["record_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`record_id is missing from object`)

		return NewRecordsValueUnknown(), diags
	}

	recordIdVal, ok := recordIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`record_id expected to be basetypes.StringValue, was: %T`, recordIdAttribute))
	}

	recordNameAttribute, ok := attributes["record_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`record_name is missing from object`)

		return NewRecordsValueUnknown(), diags
	}

	recordNameVal, ok := recordNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`record_name expected to be basetypes.StringValue, was: %T`, recordNameAttribute))
	}

	recordPriorityAttribute, ok := attributes["record_priority"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`record_priority is missing from object`)

		return NewRecordsValueUnknown(), diags
	}

	recordPriorityVal, ok := recordPriorityAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`record_priority expected to be basetypes.Int64Value, was: %T`, recordPriorityAttribute))
	}

	recordTtlAttribute, ok := attributes["record_ttl"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`record_ttl is missing from object`)

		return NewRecordsValueUnknown(), diags
	}

	recordTtlVal, ok := recordTtlAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`record_ttl expected to be basetypes.Int64Value, was: %T`, recordTtlAttribute))
	}

	recordTypeAttribute, ok := attributes["record_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`record_type is missing from object`)

		return NewRecordsValueUnknown(), diags
	}

	recordTypeVal, ok := recordTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`record_type expected to be basetypes.StringValue, was: %T`, recordTypeAttribute))
	}

	recordValueAttribute, ok := attributes["record_value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`record_value is missing from object`)

		return NewRecordsValueUnknown(), diags
	}

	recordValueVal, ok := recordValueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`record_value expected to be basetypes.StringValue, was: %T`, recordValueAttribute))
	}

	if diags.HasError() {
		return NewRecordsValueUnknown(), diags
	}

	return RecordsValue{
		RecordId:       recordIdVal,
		RecordName:     recordNameVal,
		RecordPriority: recordPriorityVal,
		RecordTtl:      recordTtlVal,
		RecordType:     recordTypeVal,
		RecordValue:    recordValueVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewRecordsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) RecordsValue {
	object, diags := NewRecordsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewRecordsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t RecordsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewRecordsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewRecordsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewRecordsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewRecordsValueMust(RecordsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t RecordsType) ValueType(ctx context.Context) attr.Value {
	return RecordsValue{}
}

var _ basetypes.ObjectValuable = RecordsValue{}

type RecordsValue struct {
	RecordId       basetypes.StringValue `tfsdk:"record_id"`
	RecordName     basetypes.StringValue `tfsdk:"record_name"`
	RecordPriority basetypes.Int64Value  `tfsdk:"record_priority"`
	RecordTtl      basetypes.Int64Value  `tfsdk:"record_ttl"`
	RecordType     basetypes.StringValue `tfsdk:"record_type"`
	RecordValue    basetypes.StringValue `tfsdk:"record_value"`
	state          attr.ValueState
}

func (v RecordsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["record_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["record_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["record_priority"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["record_ttl"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["record_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["record_value"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.RecordId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["record_id"] = val

		val, err = v.RecordName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["record_name"] = val

		val, err = v.RecordPriority.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["record_priority"] = val

		val, err = v.RecordTtl.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["record_ttl"] = val

		val, err = v.RecordType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["record_type"] = val

		val, err = v.RecordValue.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["record_value"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v RecordsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v RecordsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v RecordsValue) String() string {
	return "RecordsValue"
}

func (v RecordsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"record_id":       basetypes.StringType{},
		"record_name":     basetypes.StringType{},
		"record_priority": basetypes.Int64Type{},
		"record_ttl":      basetypes.Int64Type{},
		"record_type":     basetypes.StringType{},
		"record_value":    basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"record_id":       v.RecordId,
			"record_name":     v.RecordName,
			"record_priority": v.RecordPriority,
			"record_ttl":      v.RecordTtl,
			"record_type":     v.RecordType,
			"record_value":    v.RecordValue,
		})

	return objVal, diags
}

func (v RecordsValue) Equal(o attr.Value) bool {
	other, ok := o.(RecordsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.RecordId.Equal(other.RecordId) {
		return false
	}

	if !v.RecordName.Equal(other.RecordName) {
		return false
	}

	if !v.RecordPriority.Equal(other.RecordPriority) {
		return false
	}

	if !v.RecordTtl.Equal(other.RecordTtl) {
		return false
	}

	if !v.RecordType.Equal(other.RecordType) {
		return false
	}

	if !v.RecordValue.Equal(other.RecordValue) {
		return false
	}

	return true
}

func (v RecordsValue) Type(ctx context.Context) attr.Type {
	return RecordsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v RecordsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"record_id":       basetypes.StringType{},
		"record_name":     basetypes.StringType{},
		"record_priority": basetypes.Int64Type{},
		"record_ttl":      basetypes.Int64Type{},
		"record_type":     basetypes.StringType{},
		"record_value":    basetypes.StringType{},
	}
}
