// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_servers

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ServersDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"servers": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"datacenter": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"region_id": schema.StringAttribute{
									Computed:            true,
									Description:         "Region id.",
									MarkdownDescription: "Region id.",
								},
								"region_name": schema.StringAttribute{
									Computed:            true,
									Description:         "Region name.",
									MarkdownDescription: "Region name.",
								},
							},
							CustomType: DatacenterType{
								ObjectType: types.ObjectType{
									AttrTypes: DatacenterValue{}.AttributeTypes(ctx),
								},
							},
							Computed: true,
						},
						"ips": schema.ListNestedAttribute{
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"ip_address": schema.StringAttribute{
										Computed:            true,
										Description:         "The IP address.",
										MarkdownDescription: "The IP address.",
									},
									"ip_gateway": schema.StringAttribute{
										Computed:            true,
										Description:         "Gateway.",
										MarkdownDescription: "Gateway.",
									},
									"ip_id": schema.Int64Attribute{
										Computed:            true,
										Description:         "IP address id.",
										MarkdownDescription: "IP address id.",
									},
									"ip_netmask": schema.StringAttribute{
										Computed:            true,
										Description:         "Netmask.",
										MarkdownDescription: "Netmask.",
									},
									"ip_reverse": schema.StringAttribute{
										Computed:            true,
										Description:         "Reverse DNS (PTR) for the address.",
										MarkdownDescription: "Reverse DNS (PTR) for the address.",
									},
									"ip_type": schema.StringAttribute{
										Computed:            true,
										Description:         "Address type (primary or extra).",
										MarkdownDescription: "Address type (primary or extra).",
									},
									"ip_v4v6": schema.StringAttribute{
										Computed:            true,
										Description:         "Address family (ipv4 or ipv6).",
										MarkdownDescription: "Address family (ipv4 or ipv6).",
									},
								},
								CustomType: IpsType{
									ObjectType: types.ObjectType{
										AttrTypes: IpsValue{}.AttributeTypes(ctx),
									},
								},
							},
							Computed:            true,
							Description:         "IP addresses assigned to the server.",
							MarkdownDescription: "IP addresses assigned to the server.",
						},
						"order": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"order_id": schema.StringAttribute{
									Computed:            true,
									Description:         "Order id.",
									MarkdownDescription: "Order id.",
								},
								"order_number": schema.StringAttribute{
									Computed:            true,
									Description:         "Human-facing order number.",
									MarkdownDescription: "Human-facing order number.",
								},
								"order_status": schema.StringAttribute{
									Computed:            true,
									Description:         "Order status (e.g. active or cancelled).",
									MarkdownDescription: "Order status (e.g. active or cancelled).",
								},
								"product_id": schema.StringAttribute{
									Computed:            true,
									Description:         "Product id.",
									MarkdownDescription: "Product id.",
								},
								"product_name": schema.StringAttribute{
									Computed:            true,
									Description:         "Product name.",
									MarkdownDescription: "Product name.",
								},
							},
							CustomType: OrderType{
								ObjectType: types.ObjectType{
									AttrTypes: OrderValue{}.AttributeTypes(ctx),
								},
							},
							Computed: true,
						},
						"os": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"os_id": schema.Int64Attribute{
									Computed:            true,
									Description:         "OS image (version) id.",
									MarkdownDescription: "OS image (version) id.",
								},
								"os_name": schema.StringAttribute{
									Computed:            true,
									Description:         "OS image name.",
									MarkdownDescription: "OS image name.",
								},
								"os_release": schema.StringAttribute{
									Computed:            true,
									Description:         "OS release/version.",
									MarkdownDescription: "OS release/version.",
								},
							},
							CustomType: OsType{
								ObjectType: types.ObjectType{
									AttrTypes: OsValue{}.AttributeTypes(ctx),
								},
							},
							Computed: true,
						},
						"os_id": schema.StringAttribute{
							Computed:            true,
							Description:         "Installed OS image (version) id.",
							MarkdownDescription: "Installed OS image (version) id.",
						},
						"product_id": schema.StringAttribute{
							Computed:            true,
							Description:         "Product id.",
							MarkdownDescription: "Product id.",
						},
						"srv_cores": schema.Int64Attribute{
							Computed:            true,
							Description:         "Number of CPU cores.",
							MarkdownDescription: "Number of CPU cores.",
						},
						"srv_hostname": schema.StringAttribute{
							Computed:            true,
							Description:         "Server hostname.",
							MarkdownDescription: "Server hostname.",
						},
						"srv_id": schema.StringAttribute{
							Computed:            true,
							Description:         "Server id.",
							MarkdownDescription: "Server id.",
						},
						"srv_location": schema.StringAttribute{
							Computed:            true,
							Description:         "Datacenter location code.",
							MarkdownDescription: "Datacenter location code.",
						},
						"srv_name": schema.StringAttribute{
							Computed:            true,
							Description:         "Server name (FQDN).",
							MarkdownDescription: "Server name (FQDN).",
						},
						"srv_primary_ip": schema.StringAttribute{
							Computed:            true,
							Description:         "Primary IPv4 address.",
							MarkdownDescription: "Primary IPv4 address.",
						},
						"srv_ram": schema.Int64Attribute{
							Computed:            true,
							Description:         "Memory, in GB.",
							MarkdownDescription: "Memory, in GB.",
						},
						"srv_status": schema.BoolAttribute{
							Computed:            true,
							Description:         "Whether the server is running.",
							MarkdownDescription: "Whether the server is running.",
						},
						"srv_status_install": schema.BoolAttribute{
							Computed:            true,
							Description:         "Whether the server is installing.",
							MarkdownDescription: "Whether the server is installing.",
						},
						"srv_status_rescue": schema.BoolAttribute{
							Computed:            true,
							Description:         "Whether the server is in rescue mode.",
							MarkdownDescription: "Whether the server is in rescue mode.",
						},
						"srv_suspended": schema.BoolAttribute{
							Computed:            true,
							Description:         "Whether the server is suspended.",
							MarkdownDescription: "Whether the server is suspended.",
						},
						"srv_type": schema.StringAttribute{
							Computed:            true,
							Description:         "Server type (vps or dedicated).",
							MarkdownDescription: "Server type (vps or dedicated).",
						},
						"srv_vps_type": schema.StringAttribute{
							Computed:            true,
							Description:         "Virtualization type (e.g. kvm).",
							MarkdownDescription: "Virtualization type (e.g. kvm).",
						},
					},
					CustomType: ServersType{
						ObjectType: types.ObjectType{
							AttrTypes: ServersValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "Servers on the account.",
				MarkdownDescription: "Servers on the account.",
			},
		},
	}
}

type ServersModel struct {
	Servers types.List `tfsdk:"servers"`
}

var _ basetypes.ObjectTypable = ServersType{}

type ServersType struct {
	basetypes.ObjectType
}

func (t ServersType) Equal(o attr.Type) bool {
	other, ok := o.(ServersType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ServersType) String() string {
	return "ServersType"
}

func (t ServersType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	datacenterAttribute, ok := attributes["datacenter"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`datacenter is missing from object`)

		return nil, diags
	}

	datacenterVal, ok := datacenterAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`datacenter expected to be basetypes.ObjectValue, was: %T`, datacenterAttribute))
	}

	ipsAttribute, ok := attributes["ips"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ips is missing from object`)

		return nil, diags
	}

	ipsVal, ok := ipsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ips expected to be basetypes.ListValue, was: %T`, ipsAttribute))
	}

	orderAttribute, ok := attributes["order"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`order is missing from object`)

		return nil, diags
	}

	orderVal, ok := orderAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`order expected to be basetypes.ObjectValue, was: %T`, orderAttribute))
	}

	osAttribute, ok := attributes["os"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`os is missing from object`)

		return nil, diags
	}

	osVal, ok := osAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`os expected to be basetypes.ObjectValue, was: %T`, osAttribute))
	}

	osIdAttribute, ok := attributes["os_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`os_id is missing from object`)

		return nil, diags
	}

	osIdVal, ok := osIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`os_id expected to be basetypes.StringValue, was: %T`, osIdAttribute))
	}

	productIdAttribute, ok := attributes["product_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`product_id is missing from object`)

		return nil, diags
	}

	productIdVal, ok := productIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`product_id expected to be basetypes.StringValue, was: %T`, productIdAttribute))
	}

	srvCoresAttribute, ok := attributes["srv_cores"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_cores is missing from object`)

		return nil, diags
	}

	srvCoresVal, ok := srvCoresAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_cores expected to be basetypes.Int64Value, was: %T`, srvCoresAttribute))
	}

	srvHostnameAttribute, ok := attributes["srv_hostname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_hostname is missing from object`)

		return nil, diags
	}

	srvHostnameVal, ok := srvHostnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_hostname expected to be basetypes.StringValue, was: %T`, srvHostnameAttribute))
	}

	srvIdAttribute, ok := attributes["srv_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_id is missing from object`)

		return nil, diags
	}

	srvIdVal, ok := srvIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_id expected to be basetypes.StringValue, was: %T`, srvIdAttribute))
	}

	srvLocationAttribute, ok := attributes["srv_location"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_location is missing from object`)

		return nil, diags
	}

	srvLocationVal, ok := srvLocationAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_location expected to be basetypes.StringValue, was: %T`, srvLocationAttribute))
	}

	srvNameAttribute, ok := attributes["srv_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_name is missing from object`)

		return nil, diags
	}

	srvNameVal, ok := srvNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_name expected to be basetypes.StringValue, was: %T`, srvNameAttribute))
	}

	srvPrimaryIpAttribute, ok := attributes["srv_primary_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_primary_ip is missing from object`)

		return nil, diags
	}

	srvPrimaryIpVal, ok := srvPrimaryIpAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_primary_ip expected to be basetypes.StringValue, was: %T`, srvPrimaryIpAttribute))
	}

	srvRamAttribute, ok := attributes["srv_ram"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_ram is missing from object`)

		return nil, diags
	}

	srvRamVal, ok := srvRamAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_ram expected to be basetypes.Int64Value, was: %T`, srvRamAttribute))
	}

	srvStatusAttribute, ok := attributes["srv_status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_status is missing from object`)

		return nil, diags
	}

	srvStatusVal, ok := srvStatusAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_status expected to be basetypes.BoolValue, was: %T`, srvStatusAttribute))
	}

	srvStatusInstallAttribute, ok := attributes["srv_status_install"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_status_install is missing from object`)

		return nil, diags
	}

	srvStatusInstallVal, ok := srvStatusInstallAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_status_install expected to be basetypes.BoolValue, was: %T`, srvStatusInstallAttribute))
	}

	srvStatusRescueAttribute, ok := attributes["srv_status_rescue"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_status_rescue is missing from object`)

		return nil, diags
	}

	srvStatusRescueVal, ok := srvStatusRescueAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_status_rescue expected to be basetypes.BoolValue, was: %T`, srvStatusRescueAttribute))
	}

	srvSuspendedAttribute, ok := attributes["srv_suspended"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_suspended is missing from object`)

		return nil, diags
	}

	srvSuspendedVal, ok := srvSuspendedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_suspended expected to be basetypes.BoolValue, was: %T`, srvSuspendedAttribute))
	}

	srvTypeAttribute, ok := attributes["srv_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_type is missing from object`)

		return nil, diags
	}

	srvTypeVal, ok := srvTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_type expected to be basetypes.StringValue, was: %T`, srvTypeAttribute))
	}

	srvVpsTypeAttribute, ok := attributes["srv_vps_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_vps_type is missing from object`)

		return nil, diags
	}

	srvVpsTypeVal, ok := srvVpsTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_vps_type expected to be basetypes.StringValue, was: %T`, srvVpsTypeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ServersValue{
		Datacenter:       datacenterVal,
		Ips:              ipsVal,
		Order:            orderVal,
		Os:               osVal,
		OsId:             osIdVal,
		ProductId:        productIdVal,
		SrvCores:         srvCoresVal,
		SrvHostname:      srvHostnameVal,
		SrvId:            srvIdVal,
		SrvLocation:      srvLocationVal,
		SrvName:          srvNameVal,
		SrvPrimaryIp:     srvPrimaryIpVal,
		SrvRam:           srvRamVal,
		SrvStatus:        srvStatusVal,
		SrvStatusInstall: srvStatusInstallVal,
		SrvStatusRescue:  srvStatusRescueVal,
		SrvSuspended:     srvSuspendedVal,
		SrvType:          srvTypeVal,
		SrvVpsType:       srvVpsTypeVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewServersValueNull() ServersValue {
	return ServersValue{
		state: attr.ValueStateNull,
	}
}

func NewServersValueUnknown() ServersValue {
	return ServersValue{
		state: attr.ValueStateUnknown,
	}
}

func NewServersValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ServersValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ServersValue Attribute Value",
				"While creating a ServersValue value, a missing attribute value was detected. "+
					"A ServersValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ServersValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ServersValue Attribute Type",
				"While creating a ServersValue value, an invalid attribute value was detected. "+
					"A ServersValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ServersValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ServersValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ServersValue Attribute Value",
				"While creating a ServersValue value, an extra attribute value was detected. "+
					"A ServersValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ServersValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewServersValueUnknown(), diags
	}

	datacenterAttribute, ok := attributes["datacenter"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`datacenter is missing from object`)

		return NewServersValueUnknown(), diags
	}

	datacenterVal, ok := datacenterAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`datacenter expected to be basetypes.ObjectValue, was: %T`, datacenterAttribute))
	}

	ipsAttribute, ok := attributes["ips"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ips is missing from object`)

		return NewServersValueUnknown(), diags
	}

	ipsVal, ok := ipsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ips expected to be basetypes.ListValue, was: %T`, ipsAttribute))
	}

	orderAttribute, ok := attributes["order"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`order is missing from object`)

		return NewServersValueUnknown(), diags
	}

	orderVal, ok := orderAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`order expected to be basetypes.ObjectValue, was: %T`, orderAttribute))
	}

	osAttribute, ok := attributes["os"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`os is missing from object`)

		return NewServersValueUnknown(), diags
	}

	osVal, ok := osAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`os expected to be basetypes.ObjectValue, was: %T`, osAttribute))
	}

	osIdAttribute, ok := attributes["os_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`os_id is missing from object`)

		return NewServersValueUnknown(), diags
	}

	osIdVal, ok := osIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`os_id expected to be basetypes.StringValue, was: %T`, osIdAttribute))
	}

	productIdAttribute, ok := attributes["product_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`product_id is missing from object`)

		return NewServersValueUnknown(), diags
	}

	productIdVal, ok := productIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`product_id expected to be basetypes.StringValue, was: %T`, productIdAttribute))
	}

	srvCoresAttribute, ok := attributes["srv_cores"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_cores is missing from object`)

		return NewServersValueUnknown(), diags
	}

	srvCoresVal, ok := srvCoresAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_cores expected to be basetypes.Int64Value, was: %T`, srvCoresAttribute))
	}

	srvHostnameAttribute, ok := attributes["srv_hostname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_hostname is missing from object`)

		return NewServersValueUnknown(), diags
	}

	srvHostnameVal, ok := srvHostnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_hostname expected to be basetypes.StringValue, was: %T`, srvHostnameAttribute))
	}

	srvIdAttribute, ok := attributes["srv_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_id is missing from object`)

		return NewServersValueUnknown(), diags
	}

	srvIdVal, ok := srvIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_id expected to be basetypes.StringValue, was: %T`, srvIdAttribute))
	}

	srvLocationAttribute, ok := attributes["srv_location"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_location is missing from object`)

		return NewServersValueUnknown(), diags
	}

	srvLocationVal, ok := srvLocationAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_location expected to be basetypes.StringValue, was: %T`, srvLocationAttribute))
	}

	srvNameAttribute, ok := attributes["srv_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_name is missing from object`)

		return NewServersValueUnknown(), diags
	}

	srvNameVal, ok := srvNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_name expected to be basetypes.StringValue, was: %T`, srvNameAttribute))
	}

	srvPrimaryIpAttribute, ok := attributes["srv_primary_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_primary_ip is missing from object`)

		return NewServersValueUnknown(), diags
	}

	srvPrimaryIpVal, ok := srvPrimaryIpAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_primary_ip expected to be basetypes.StringValue, was: %T`, srvPrimaryIpAttribute))
	}

	srvRamAttribute, ok := attributes["srv_ram"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_ram is missing from object`)

		return NewServersValueUnknown(), diags
	}

	srvRamVal, ok := srvRamAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_ram expected to be basetypes.Int64Value, was: %T`, srvRamAttribute))
	}

	srvStatusAttribute, ok := attributes["srv_status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_status is missing from object`)

		return NewServersValueUnknown(), diags
	}

	srvStatusVal, ok := srvStatusAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_status expected to be basetypes.BoolValue, was: %T`, srvStatusAttribute))
	}

	srvStatusInstallAttribute, ok := attributes["srv_status_install"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_status_install is missing from object`)

		return NewServersValueUnknown(), diags
	}

	srvStatusInstallVal, ok := srvStatusInstallAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_status_install expected to be basetypes.BoolValue, was: %T`, srvStatusInstallAttribute))
	}

	srvStatusRescueAttribute, ok := attributes["srv_status_rescue"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_status_rescue is missing from object`)

		return NewServersValueUnknown(), diags
	}

	srvStatusRescueVal, ok := srvStatusRescueAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_status_rescue expected to be basetypes.BoolValue, was: %T`, srvStatusRescueAttribute))
	}

	srvSuspendedAttribute, ok := attributes["srv_suspended"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_suspended is missing from object`)

		return NewServersValueUnknown(), diags
	}

	srvSuspendedVal, ok := srvSuspendedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_suspended expected to be basetypes.BoolValue, was: %T`, srvSuspendedAttribute))
	}

	srvTypeAttribute, ok := attributes["srv_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_type is missing from object`)

		return NewServersValueUnknown(), diags
	}

	srvTypeVal, ok := srvTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_type expected to be basetypes.StringValue, was: %T`, srvTypeAttribute))
	}

	srvVpsTypeAttribute, ok := attributes["srv_vps_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`srv_vps_type is missing from object`)

		return NewServersValueUnknown(), diags
	}

	srvVpsTypeVal, ok := srvVpsTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`srv_vps_type expected to be basetypes.StringValue, was: %T`, srvVpsTypeAttribute))
	}

	if diags.HasError() {
		return NewServersValueUnknown(), diags
	}

	return ServersValue{
		Datacenter:       datacenterVal,
		Ips:              ipsVal,
		Order:            orderVal,
		Os:               osVal,
		OsId:             osIdVal,
		ProductId:        productIdVal,
		SrvCores:         srvCoresVal,
		SrvHostname:      srvHostnameVal,
		SrvId:            srvIdVal,
		SrvLocation:      srvLocationVal,
		SrvName:          srvNameVal,
		SrvPrimaryIp:     srvPrimaryIpVal,
		SrvRam:           srvRamVal,
		SrvStatus:        srvStatusVal,
		SrvStatusInstall: srvStatusInstallVal,
		SrvStatusRescue:  srvStatusRescueVal,
		SrvSuspended:     srvSuspendedVal,
		SrvType:          srvTypeVal,
		SrvVpsType:       srvVpsTypeVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewServersValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ServersValue {
	object, diags := NewServersValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewServersValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ServersType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewServersValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewServersValueUnknown(), nil
	}

	if in.IsNull() {
		return NewServersValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewServersValueMust(ServersValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ServersType) ValueType(ctx context.Context) attr.Value {
	return ServersValue{}
}

var _ basetypes.ObjectValuable = ServersValue{}

type ServersValue struct {
	Datacenter       basetypes.ObjectValue `tfsdk:"datacenter"`
	Ips              basetypes.ListValue   `tfsdk:"ips"`
	Order            basetypes.ObjectValue `tfsdk:"order"`
	Os               basetypes.ObjectValue `tfsdk:"os"`
	OsId             basetypes.StringValue `tfsdk:"os_id"`
	ProductId        basetypes.StringValue `tfsdk:"product_id"`
	SrvCores         basetypes.Int64Value  `tfsdk:"srv_cores"`
	SrvHostname      basetypes.StringValue `tfsdk:"srv_hostname"`
	SrvId            basetypes.StringValue `tfsdk:"srv_id"`
	SrvLocation      basetypes.StringValue `tfsdk:"srv_location"`
	SrvName          basetypes.StringValue `tfsdk:"srv_name"`
	SrvPrimaryIp     basetypes.StringValue `tfsdk:"srv_primary_ip"`
	SrvRam           basetypes.Int64Value  `tfsdk:"srv_ram"`
	SrvStatus        basetypes.BoolValue   `tfsdk:"srv_status"`
	SrvStatusInstall basetypes.BoolValue   `tfsdk:"srv_status_install"`
	SrvStatusRescue  basetypes.BoolValue   `tfsdk:"srv_status_rescue"`
	SrvSuspended     basetypes.BoolValue   `tfsdk:"srv_suspended"`
	SrvType          basetypes.StringValue `tfsdk:"srv_type"`
	SrvVpsType       basetypes.StringValue `tfsdk:"srv_vps_type"`
	state            attr.ValueState
}

func (v ServersValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 19)

	var val tftypes.Value
	var err error

	attrTypes["datacenter"] = basetypes.ObjectType{
		AttrTypes: DatacenterValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["ips"] = basetypes.ListType{
		ElemType: IpsValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["order"] = basetypes.ObjectType{
		AttrTypes: OrderValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["os"] = basetypes.ObjectType{
		AttrTypes: OsValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["os_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["product_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["srv_cores"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["srv_hostname"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["srv_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["srv_location"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["srv_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["srv_primary_ip"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["srv_ram"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["srv_status"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["srv_status_install"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["srv_status_rescue"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["srv_suspended"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["srv_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["srv_vps_type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 19)

		val, err = v.Datacenter.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["datacenter"] = val

		val, err = v.Ips.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ips"] = val

		val, err = v.Order.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["order"] = val

		val, err = v.Os.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["os"] = val

		val, err = v.OsId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["os_id"] = val

		val, err = v.ProductId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["product_id"] = val

		val, err = v.SrvCores.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["srv_cores"] = val

		val, err = v.SrvHostname.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["srv_hostname"] = val

		val, err = v.SrvId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["srv_id"] = val

		val, err = v.SrvLocation.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["srv_location"] = val

		val, err = v.SrvName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["srv_name"] = val

		val, err = v.SrvPrimaryIp.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["srv_primary_ip"] = val

		val, err = v.SrvRam.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["srv_ram"] = val

		val, err = v.SrvStatus.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["srv_status"] = val

		val, err = v.SrvStatusInstall.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["srv_status_install"] = val

		val, err = v.SrvStatusRescue.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["srv_status_rescue"] = val

		val, err = v.SrvSuspended.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["srv_suspended"] = val

		val, err = v.SrvType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["srv_type"] = val

		val, err = v.SrvVpsType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["srv_vps_type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ServersValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ServersValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ServersValue) String() string {
	return "ServersValue"
}

func (v ServersValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var datacenter basetypes.ObjectValue

	if v.Datacenter.IsNull() {
		datacenter = types.ObjectNull(
			DatacenterValue{}.AttributeTypes(ctx),
		)
	}

	if v.Datacenter.IsUnknown() {
		datacenter = types.ObjectUnknown(
			DatacenterValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Datacenter.IsNull() && !v.Datacenter.IsUnknown() {
		datacenter = types.ObjectValueMust(
			DatacenterValue{}.AttributeTypes(ctx),
			v.Datacenter.Attributes(),
		)
	}

	ips := types.ListValueMust(
		IpsType{
			basetypes.ObjectType{
				AttrTypes: IpsValue{}.AttributeTypes(ctx),
			},
		},
		v.Ips.Elements(),
	)

	if v.Ips.IsNull() {
		ips = types.ListNull(
			IpsType{
				basetypes.ObjectType{
					AttrTypes: IpsValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.Ips.IsUnknown() {
		ips = types.ListUnknown(
			IpsType{
				basetypes.ObjectType{
					AttrTypes: IpsValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	var order basetypes.ObjectValue

	if v.Order.IsNull() {
		order = types.ObjectNull(
			OrderValue{}.AttributeTypes(ctx),
		)
	}

	if v.Order.IsUnknown() {
		order = types.ObjectUnknown(
			OrderValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Order.IsNull() && !v.Order.IsUnknown() {
		order = types.ObjectValueMust(
			OrderValue{}.AttributeTypes(ctx),
			v.Order.Attributes(),
		)
	}

	var os basetypes.ObjectValue

	if v.Os.IsNull() {
		os = types.ObjectNull(
			OsValue{}.AttributeTypes(ctx),
		)
	}

	if v.Os.IsUnknown() {
		os = types.ObjectUnknown(
			OsValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Os.IsNull() && !v.Os.IsUnknown() {
		os = types.ObjectValueMust(
			OsValue{}.AttributeTypes(ctx),
			v.Os.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"datacenter": basetypes.ObjectType{
			AttrTypes: DatacenterValue{}.AttributeTypes(ctx),
		},
		"ips": basetypes.ListType{
			ElemType: IpsValue{}.Type(ctx),
		},
		"order": basetypes.ObjectType{
			AttrTypes: OrderValue{}.AttributeTypes(ctx),
		},
		"os": basetypes.ObjectType{
			AttrTypes: OsValue{}.AttributeTypes(ctx),
		},
		"os_id":              basetypes.StringType{},
		"product_id":         basetypes.StringType{},
		"srv_cores":          basetypes.Int64Type{},
		"srv_hostname":       basetypes.StringType{},
		"srv_id":             basetypes.StringType{},
		"srv_location":       basetypes.StringType{},
		"srv_name":           basetypes.StringType{},
		"srv_primary_ip":     basetypes.StringType{},
		"srv_ram":            basetypes.Int64Type{},
		"srv_status":         basetypes.BoolType{},
		"srv_status_install": basetypes.BoolType{},
		"srv_status_rescue":  basetypes.BoolType{},
		"srv_suspended":      basetypes.BoolType{},
		"srv_type":           basetypes.StringType{},
		"srv_vps_type":       basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"datacenter":         datacenter,
			"ips":                ips,
			"order":              order,
			"os":                 os,
			"os_id":              v.OsId,
			"product_id":         v.ProductId,
			"srv_cores":          v.SrvCores,
			"srv_hostname":       v.SrvHostname,
			"srv_id":             v.SrvId,
			"srv_location":       v.SrvLocation,
			"srv_name":           v.SrvName,
			"srv_primary_ip":     v.SrvPrimaryIp,
			"srv_ram":            v.SrvRam,
			"srv_status":         v.SrvStatus,
			"srv_status_install": v.SrvStatusInstall,
			"srv_status_rescue":  v.SrvStatusRescue,
			"srv_suspended":      v.SrvSuspended,
			"srv_type":           v.SrvType,
			"srv_vps_type":       v.SrvVpsType,
		})

	return objVal, diags
}

func (v ServersValue) Equal(o attr.Value) bool {
	other, ok := o.(ServersValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Datacenter.Equal(other.Datacenter) {
		return false
	}

	if !v.Ips.Equal(other.Ips) {
		return false
	}

	if !v.Order.Equal(other.Order) {
		return false
	}

	if !v.Os.Equal(other.Os) {
		return false
	}

	if !v.OsId.Equal(other.OsId) {
		return false
	}

	if !v.ProductId.Equal(other.ProductId) {
		return false
	}

	if !v.SrvCores.Equal(other.SrvCores) {
		return false
	}

	if !v.SrvHostname.Equal(other.SrvHostname) {
		return false
	}

	if !v.SrvId.Equal(other.SrvId) {
		return false
	}

	if !v.SrvLocation.Equal(other.SrvLocation) {
		return false
	}

	if !v.SrvName.Equal(other.SrvName) {
		return false
	}

	if !v.SrvPrimaryIp.Equal(other.SrvPrimaryIp) {
		return false
	}

	if !v.SrvRam.Equal(other.SrvRam) {
		return false
	}

	if !v.SrvStatus.Equal(other.SrvStatus) {
		return false
	}

	if !v.SrvStatusInstall.Equal(other.SrvStatusInstall) {
		return false
	}

	if !v.SrvStatusRescue.Equal(other.SrvStatusRescue) {
		return false
	}

	if !v.SrvSuspended.Equal(other.SrvSuspended) {
		return false
	}

	if !v.SrvType.Equal(other.SrvType) {
		return false
	}

	if !v.SrvVpsType.Equal(other.SrvVpsType) {
		return false
	}

	return true
}

func (v ServersValue) Type(ctx context.Context) attr.Type {
	return ServersType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ServersValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"datacenter": basetypes.ObjectType{
			AttrTypes: DatacenterValue{}.AttributeTypes(ctx),
		},
		"ips": basetypes.ListType{
			ElemType: IpsValue{}.Type(ctx),
		},
		"order": basetypes.ObjectType{
			AttrTypes: OrderValue{}.AttributeTypes(ctx),
		},
		"os": basetypes.ObjectType{
			AttrTypes: OsValue{}.AttributeTypes(ctx),
		},
		"os_id":              basetypes.StringType{},
		"product_id":         basetypes.StringType{},
		"srv_cores":          basetypes.Int64Type{},
		"srv_hostname":       basetypes.StringType{},
		"srv_id":             basetypes.StringType{},
		"srv_location":       basetypes.StringType{},
		"srv_name":           basetypes.StringType{},
		"srv_primary_ip":     basetypes.StringType{},
		"srv_ram":            basetypes.Int64Type{},
		"srv_status":         basetypes.BoolType{},
		"srv_status_install": basetypes.BoolType{},
		"srv_status_rescue":  basetypes.BoolType{},
		"srv_suspended":      basetypes.BoolType{},
		"srv_type":           basetypes.StringType{},
		"srv_vps_type":       basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = DatacenterType{}

type DatacenterType struct {
	basetypes.ObjectType
}

func (t DatacenterType) Equal(o attr.Type) bool {
	other, ok := o.(DatacenterType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DatacenterType) String() string {
	return "DatacenterType"
}

func (t DatacenterType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	regionIdAttribute, ok := attributes["region_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_id is missing from object`)

		return nil, diags
	}

	regionIdVal, ok := regionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_id expected to be basetypes.StringValue, was: %T`, regionIdAttribute))
	}

	regionNameAttribute, ok := attributes["region_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_name is missing from object`)

		return nil, diags
	}

	regionNameVal, ok := regionNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_name expected to be basetypes.StringValue, was: %T`, regionNameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DatacenterValue{
		RegionId:   regionIdVal,
		RegionName: regionNameVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewDatacenterValueNull() DatacenterValue {
	return DatacenterValue{
		state: attr.ValueStateNull,
	}
}

func NewDatacenterValueUnknown() DatacenterValue {
	return DatacenterValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDatacenterValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DatacenterValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DatacenterValue Attribute Value",
				"While creating a DatacenterValue value, a missing attribute value was detected. "+
					"A DatacenterValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DatacenterValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DatacenterValue Attribute Type",
				"While creating a DatacenterValue value, an invalid attribute value was detected. "+
					"A DatacenterValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DatacenterValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DatacenterValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DatacenterValue Attribute Value",
				"While creating a DatacenterValue value, an extra attribute value was detected. "+
					"A DatacenterValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DatacenterValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDatacenterValueUnknown(), diags
	}

	regionIdAttribute, ok := attributes["region_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_id is missing from object`)

		return NewDatacenterValueUnknown(), diags
	}

	regionIdVal, ok := regionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_id expected to be basetypes.StringValue, was: %T`, regionIdAttribute))
	}

	regionNameAttribute, ok := attributes["region_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_name is missing from object`)

		return NewDatacenterValueUnknown(), diags
	}

	regionNameVal, ok := regionNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_name expected to be basetypes.StringValue, was: %T`, regionNameAttribute))
	}

	if diags.HasError() {
		return NewDatacenterValueUnknown(), diags
	}

	return DatacenterValue{
		RegionId:   regionIdVal,
		RegionName: regionNameVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewDatacenterValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DatacenterValue {
	object, diags := NewDatacenterValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDatacenterValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DatacenterType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDatacenterValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDatacenterValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDatacenterValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDatacenterValueMust(DatacenterValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DatacenterType) ValueType(ctx context.Context) attr.Value {
	return DatacenterValue{}
}

var _ basetypes.ObjectValuable = DatacenterValue{}

type DatacenterValue struct {
	RegionId   basetypes.StringValue `tfsdk:"region_id"`
	RegionName basetypes.StringValue `tfsdk:"region_name"`
	state      attr.ValueState
}

func (v DatacenterValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["region_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["region_name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.RegionId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region_id"] = val

		val, err = v.RegionName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region_name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DatacenterValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DatacenterValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DatacenterValue) String() string {
	return "DatacenterValue"
}

func (v DatacenterValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"region_id":   basetypes.StringType{},
		"region_name": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"region_id":   v.RegionId,
			"region_name": v.RegionName,
		})

	return objVal, diags
}

func (v DatacenterValue) Equal(o attr.Value) bool {
	other, ok := o.(DatacenterValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.RegionId.Equal(other.RegionId) {
		return false
	}

	if !v.RegionName.Equal(other.RegionName) {
		return false
	}

	return true
}

func (v DatacenterValue) Type(ctx context.Context) attr.Type {
	return DatacenterType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DatacenterValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"region_id":   basetypes.StringType{},
		"region_name": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = IpsType{}

type IpsType struct {
	basetypes.ObjectType
}

func (t IpsType) Equal(o attr.Type) bool {
	other, ok := o.(IpsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t IpsType) String() string {
	return "IpsType"
}

func (t IpsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	ipAddressAttribute, ok := attributes["ip_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_address is missing from object`)

		return nil, diags
	}

	ipAddressVal, ok := ipAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_address expected to be basetypes.StringValue, was: %T`, ipAddressAttribute))
	}

	ipGatewayAttribute, ok := attributes["ip_gateway"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_gateway is missing from object`)

		return nil, diags
	}

	ipGatewayVal, ok := ipGatewayAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_gateway expected to be basetypes.StringValue, was: %T`, ipGatewayAttribute))
	}

	ipIdAttribute, ok := attributes["ip_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_id is missing from object`)

		return nil, diags
	}

	ipIdVal, ok := ipIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_id expected to be basetypes.Int64Value, was: %T`, ipIdAttribute))
	}

	ipNetmaskAttribute, ok := attributes["ip_netmask"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_netmask is missing from object`)

		return nil, diags
	}

	ipNetmaskVal, ok := ipNetmaskAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_netmask expected to be basetypes.StringValue, was: %T`, ipNetmaskAttribute))
	}

	ipReverseAttribute, ok := attributes["ip_reverse"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_reverse is missing from object`)

		return nil, diags
	}

	ipReverseVal, ok := ipReverseAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_reverse expected to be basetypes.StringValue, was: %T`, ipReverseAttribute))
	}

	ipTypeAttribute, ok := attributes["ip_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_type is missing from object`)

		return nil, diags
	}

	ipTypeVal, ok := ipTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_type expected to be basetypes.StringValue, was: %T`, ipTypeAttribute))
	}

	ipV4v6Attribute, ok := attributes["ip_v4v6"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_v4v6 is missing from object`)

		return nil, diags
	}

	ipV4v6Val, ok := ipV4v6Attribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_v4v6 expected to be basetypes.StringValue, was: %T`, ipV4v6Attribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return IpsValue{
		IpAddress: ipAddressVal,
		IpGateway: ipGatewayVal,
		IpId:      ipIdVal,
		IpNetmask: ipNetmaskVal,
		IpReverse: ipReverseVal,
		IpType:    ipTypeVal,
		IpV4v6:    ipV4v6Val,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewIpsValueNull() IpsValue {
	return IpsValue{
		state: attr.ValueStateNull,
	}
}

func NewIpsValueUnknown() IpsValue {
	return IpsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewIpsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (IpsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing IpsValue Attribute Value",
				"While creating a IpsValue value, a missing attribute value was detected. "+
					"A IpsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IpsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid IpsValue Attribute Type",
				"While creating a IpsValue value, an invalid attribute value was detected. "+
					"A IpsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IpsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("IpsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra IpsValue Attribute Value",
				"While creating a IpsValue value, an extra attribute value was detected. "+
					"A IpsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra IpsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewIpsValueUnknown(), diags
	}

	ipAddressAttribute, ok := attributes["ip_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_address is missing from object`)

		return NewIpsValueUnknown(), diags
	}

	ipAddressVal, ok := ipAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_address expected to be basetypes.StringValue, was: %T`, ipAddressAttribute))
	}

	ipGatewayAttribute, ok := attributes["ip_gateway"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_gateway is missing from object`)

		return NewIpsValueUnknown(), diags
	}

	ipGatewayVal, ok := ipGatewayAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_gateway expected to be basetypes.StringValue, was: %T`, ipGatewayAttribute))
	}

	ipIdAttribute, ok := attributes["ip_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_id is missing from object`)

		return NewIpsValueUnknown(), diags
	}

	ipIdVal, ok := ipIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_id expected to be basetypes.Int64Value, was: %T`, ipIdAttribute))
	}

	ipNetmaskAttribute, ok := attributes["ip_netmask"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_netmask is missing from object`)

		return NewIpsValueUnknown(), diags
	}

	ipNetmaskVal, ok := ipNetmaskAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_netmask expected to be basetypes.StringValue, was: %T`, ipNetmaskAttribute))
	}

	ipReverseAttribute, ok := attributes["ip_reverse"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_reverse is missing from object`)

		return NewIpsValueUnknown(), diags
	}

	ipReverseVal, ok := ipReverseAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_reverse expected to be basetypes.StringValue, was: %T`, ipReverseAttribute))
	}

	ipTypeAttribute, ok := attributes["ip_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_type is missing from object`)

		return NewIpsValueUnknown(), diags
	}

	ipTypeVal, ok := ipTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_type expected to be basetypes.StringValue, was: %T`, ipTypeAttribute))
	}

	ipV4v6Attribute, ok := attributes["ip_v4v6"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_v4v6 is missing from object`)

		return NewIpsValueUnknown(), diags
	}

	ipV4v6Val, ok := ipV4v6Attribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_v4v6 expected to be basetypes.StringValue, was: %T`, ipV4v6Attribute))
	}

	if diags.HasError() {
		return NewIpsValueUnknown(), diags
	}

	return IpsValue{
		IpAddress: ipAddressVal,
		IpGateway: ipGatewayVal,
		IpId:      ipIdVal,
		IpNetmask: ipNetmaskVal,
		IpReverse: ipReverseVal,
		IpType:    ipTypeVal,
		IpV4v6:    ipV4v6Val,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewIpsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) IpsValue {
	object, diags := NewIpsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewIpsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t IpsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewIpsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewIpsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewIpsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewIpsValueMust(IpsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t IpsType) ValueType(ctx context.Context) attr.Value {
	return IpsValue{}
}

var _ basetypes.ObjectValuable = IpsValue{}

type IpsValue struct {
	IpAddress basetypes.StringValue `tfsdk:"ip_address"`
	IpGateway basetypes.StringValue `tfsdk:"ip_gateway"`
	IpId      basetypes.Int64Value  `tfsdk:"ip_id"`
	IpNetmask basetypes.StringValue `tfsdk:"ip_netmask"`
	IpReverse basetypes.StringValue `tfsdk:"ip_reverse"`
	IpType    basetypes.StringValue `tfsdk:"ip_type"`
	IpV4v6    basetypes.StringValue `tfsdk:"ip_v4v6"`
	state     attr.ValueState
}

func (v IpsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 7)

	var val tftypes.Value
	var err error

	attrTypes["ip_address"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["ip_gateway"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["ip_id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["ip_netmask"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["ip_reverse"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["ip_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["ip_v4v6"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 7)

		val, err = v.IpAddress.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip_address"] = val

		val, err = v.IpGateway.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip_gateway"] = val

		val, err = v.IpId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip_id"] = val

		val, err = v.IpNetmask.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip_netmask"] = val

		val, err = v.IpReverse.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip_reverse"] = val

		val, err = v.IpType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip_type"] = val

		val, err = v.IpV4v6.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip_v4v6"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v IpsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v IpsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v IpsValue) String() string {
	return "IpsValue"
}

func (v IpsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"ip_address": basetypes.StringType{},
		"ip_gateway": basetypes.StringType{},
		"ip_id":      basetypes.Int64Type{},
		"ip_netmask": basetypes.StringType{},
		"ip_reverse": basetypes.StringType{},
		"ip_type":    basetypes.StringType{},
		"ip_v4v6":    basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"ip_address": v.IpAddress,
			"ip_gateway": v.IpGateway,
			"ip_id":      v.IpId,
			"ip_netmask": v.IpNetmask,
			"ip_reverse": v.IpReverse,
			"ip_type":    v.IpType,
			"ip_v4v6":    v.IpV4v6,
		})

	return objVal, diags
}

func (v IpsValue) Equal(o attr.Value) bool {
	other, ok := o.(IpsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.IpAddress.Equal(other.IpAddress) {
		return false
	}

	if !v.IpGateway.Equal(other.IpGateway) {
		return false
	}

	if !v.IpId.Equal(other.IpId) {
		return false
	}

	if !v.IpNetmask.Equal(other.IpNetmask) {
		return false
	}

	if !v.IpReverse.Equal(other.IpReverse) {
		return false
	}

	if !v.IpType.Equal(other.IpType) {
		return false
	}

	if !v.IpV4v6.Equal(other.IpV4v6) {
		return false
	}

	return true
}

func (v IpsValue) Type(ctx context.Context) attr.Type {
	return IpsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v IpsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"ip_address": basetypes.StringType{},
		"ip_gateway": basetypes.StringType{},
		"ip_id":      basetypes.Int64Type{},
		"ip_netmask": basetypes.StringType{},
		"ip_reverse": basetypes.StringType{},
		"ip_type":    basetypes.StringType{},
		"ip_v4v6":    basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = OrderType{}

type OrderType struct {
	basetypes.ObjectType
}

func (t OrderType) Equal(o attr.Type) bool {
	other, ok := o.(OrderType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t OrderType) String() string {
	return "OrderType"
}

func (t OrderType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	orderIdAttribute, ok := attributes["order_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`order_id is missing from object`)

		return nil, diags
	}

	orderIdVal, ok := orderIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`order_id expected to be basetypes.StringValue, was: %T`, orderIdAttribute))
	}

	orderNumberAttribute, ok := attributes["order_number"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`order_number is missing from object`)

		return nil, diags
	}

	orderNumberVal, ok := orderNumberAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`order_number expected to be basetypes.StringValue, was: %T`, orderNumberAttribute))
	}

	orderStatusAttribute, ok := attributes["order_status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`order_status is missing from object`)

		return nil, diags
	}

	orderStatusVal, ok := orderStatusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`order_status expected to be basetypes.StringValue, was: %T`, orderStatusAttribute))
	}

	productIdAttribute, ok := attributes["product_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`product_id is missing from object`)

		return nil, diags
	}

	productIdVal, ok := productIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`product_id expected to be basetypes.StringValue, was: %T`, productIdAttribute))
	}

	productNameAttribute, ok := attributes["product_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`product_name is missing from object`)

		return nil, diags
	}

	productNameVal, ok := productNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`product_name expected to be basetypes.StringValue, was: %T`, productNameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return OrderValue{
		OrderId:     orderIdVal,
		OrderNumber: orderNumberVal,
		OrderStatus: orderStatusVal,
		ProductId:   productIdVal,
		ProductName: productNameVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewOrderValueNull() OrderValue {
	return OrderValue{
		state: attr.ValueStateNull,
	}
}

func NewOrderValueUnknown() OrderValue {
	return OrderValue{
		state: attr.ValueStateUnknown,
	}
}

func NewOrderValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (OrderValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing OrderValue Attribute Value",
				"While creating a OrderValue value, a missing attribute value was detected. "+
					"A OrderValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OrderValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid OrderValue Attribute Type",
				"While creating a OrderValue value, an invalid attribute value was detected. "+
					"A OrderValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OrderValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("OrderValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra OrderValue Attribute Value",
				"While creating a OrderValue value, an extra attribute value was detected. "+
					"A OrderValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra OrderValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewOrderValueUnknown(), diags
	}

	orderIdAttribute, ok := attributes["order_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`order_id is missing from object`)

		return NewOrderValueUnknown(), diags
	}

	orderIdVal, ok := orderIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`order_id expected to be basetypes.StringValue, was: %T`, orderIdAttribute))
	}

	orderNumberAttribute, ok := attributes["order_number"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`order_number is missing from object`)

		return NewOrderValueUnknown(), diags
	}

	orderNumberVal, ok := orderNumberAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`order_number expected to be basetypes.StringValue, was: %T`, orderNumberAttribute))
	}

	orderStatusAttribute, ok := attributes["order_status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`order_status is missing from object`)

		return NewOrderValueUnknown(), diags
	}

	orderStatusVal, ok := orderStatusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`order_status expected to be basetypes.StringValue, was: %T`, orderStatusAttribute))
	}

	productIdAttribute, ok := attributes["product_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`product_id is missing from object`)

		return NewOrderValueUnknown(), diags
	}

	productIdVal, ok := productIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`product_id expected to be basetypes.StringValue, was: %T`, productIdAttribute))
	}

	productNameAttribute, ok := attributes["product_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`product_name is missing from object`)

		return NewOrderValueUnknown(), diags
	}

	productNameVal, ok := productNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`product_name expected to be basetypes.StringValue, was: %T`, productNameAttribute))
	}

	if diags.HasError() {
		return NewOrderValueUnknown(), diags
	}

	return OrderValue{
		OrderId:     orderIdVal,
		OrderNumber: orderNumberVal,
		OrderStatus: orderStatusVal,
		ProductId:   productIdVal,
		ProductName: productNameVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewOrderValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) OrderValue {
	object, diags := NewOrderValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewOrderValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t OrderType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewOrderValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewOrderValueUnknown(), nil
	}

	if in.IsNull() {
		return NewOrderValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewOrderValueMust(OrderValue{}.AttributeTypes(ctx), attributes), nil
}

func (t OrderType) ValueType(ctx context.Context) attr.Value {
	return OrderValue{}
}

var _ basetypes.ObjectValuable = OrderValue{}

type OrderValue struct {
	OrderId     basetypes.StringValue `tfsdk:"order_id"`
	OrderNumber basetypes.StringValue `tfsdk:"order_number"`
	OrderStatus basetypes.StringValue `tfsdk:"order_status"`
	ProductId   basetypes.StringValue `tfsdk:"product_id"`
	ProductName basetypes.StringValue `tfsdk:"product_name"`
	state       attr.ValueState
}

func (v OrderValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["order_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["order_number"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["order_status"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["product_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["product_name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.OrderId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["order_id"] = val

		val, err = v.OrderNumber.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["order_number"] = val

		val, err = v.OrderStatus.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["order_status"] = val

		val, err = v.ProductId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["product_id"] = val

		val, err = v.ProductName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["product_name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v OrderValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v OrderValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v OrderValue) String() string {
	return "OrderValue"
}

func (v OrderValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"order_id":     basetypes.StringType{},
		"order_number": basetypes.StringType{},
		"order_status": basetypes.StringType{},
		"product_id":   basetypes.StringType{},
		"product_name": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"order_id":     v.OrderId,
			"order_number": v.OrderNumber,
			"order_status": v.OrderStatus,
			"product_id":   v.ProductId,
			"product_name": v.ProductName,
		})

	return objVal, diags
}

func (v OrderValue) Equal(o attr.Value) bool {
	other, ok := o.(OrderValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.OrderId.Equal(other.OrderId) {
		return false
	}

	if !v.OrderNumber.Equal(other.OrderNumber) {
		return false
	}

	if !v.OrderStatus.Equal(other.OrderStatus) {
		return false
	}

	if !v.ProductId.Equal(other.ProductId) {
		return false
	}

	if !v.ProductName.Equal(other.ProductName) {
		return false
	}

	return true
}

func (v OrderValue) Type(ctx context.Context) attr.Type {
	return OrderType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v OrderValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"order_id":     basetypes.StringType{},
		"order_number": basetypes.StringType{},
		"order_status": basetypes.StringType{},
		"product_id":   basetypes.StringType{},
		"product_name": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = OsType{}

type OsType struct {
	basetypes.ObjectType
}

func (t OsType) Equal(o attr.Type) bool {
	other, ok := o.(OsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t OsType) String() string {
	return "OsType"
}

func (t OsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	osIdAttribute, ok := attributes["os_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`os_id is missing from object`)

		return nil, diags
	}

	osIdVal, ok := osIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`os_id expected to be basetypes.Int64Value, was: %T`, osIdAttribute))
	}

	osNameAttribute, ok := attributes["os_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`os_name is missing from object`)

		return nil, diags
	}

	osNameVal, ok := osNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`os_name expected to be basetypes.StringValue, was: %T`, osNameAttribute))
	}

	osReleaseAttribute, ok := attributes["os_release"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`os_release is missing from object`)

		return nil, diags
	}

	osReleaseVal, ok := osReleaseAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`os_release expected to be basetypes.StringValue, was: %T`, osReleaseAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return OsValue{
		OsId:      osIdVal,
		OsName:    osNameVal,
		OsRelease: osReleaseVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewOsValueNull() OsValue {
	return OsValue{
		state: attr.ValueStateNull,
	}
}

func NewOsValueUnknown() OsValue {
	return OsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewOsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (OsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing OsValue Attribute Value",
				"While creating a OsValue value, a missing attribute value was detected. "+
					"A OsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid OsValue Attribute Type",
				"While creating a OsValue value, an invalid attribute value was detected. "+
					"A OsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("OsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra OsValue Attribute Value",
				"While creating a OsValue value, an extra attribute value was detected. "+
					"A OsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra OsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewOsValueUnknown(), diags
	}

	osIdAttribute, ok := attributes["os_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`os_id is missing from object`)

		return NewOsValueUnknown(), diags
	}

	osIdVal, ok := osIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`os_id expected to be basetypes.Int64Value, was: %T`, osIdAttribute))
	}

	osNameAttribute, ok := attributes["os_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`os_name is missing from object`)

		return NewOsValueUnknown(), diags
	}

	osNameVal, ok := osNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`os_name expected to be basetypes.StringValue, was: %T`, osNameAttribute))
	}

	osReleaseAttribute, ok := attributes["os_release"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`os_release is missing from object`)

		return NewOsValueUnknown(), diags
	}

	osReleaseVal, ok := osReleaseAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`os_release expected to be basetypes.StringValue, was: %T`, osReleaseAttribute))
	}

	if diags.HasError() {
		return NewOsValueUnknown(), diags
	}

	return OsValue{
		OsId:      osIdVal,
		OsName:    osNameVal,
		OsRelease: osReleaseVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewOsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) OsValue {
	object, diags := NewOsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewOsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t OsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewOsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewOsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewOsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewOsValueMust(OsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t OsType) ValueType(ctx context.Context) attr.Value {
	return OsValue{}
}

var _ basetypes.ObjectValuable = OsValue{}

type OsValue struct {
	OsId      basetypes.Int64Value  `tfsdk:"os_id"`
	OsName    basetypes.StringValue `tfsdk:"os_name"`
	OsRelease basetypes.StringValue `tfsdk:"os_release"`
	state     attr.ValueState
}

func (v OsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["os_id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["os_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["os_release"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.OsId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["os_id"] = val

		val, err = v.OsName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["os_name"] = val

		val, err = v.OsRelease.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["os_release"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v OsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v OsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v OsValue) String() string {
	return "OsValue"
}

func (v OsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"os_id":      basetypes.Int64Type{},
		"os_name":    basetypes.StringType{},
		"os_release": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"os_id":      v.OsId,
			"os_name":    v.OsName,
			"os_release": v.OsRelease,
		})

	return objVal, diags
}

func (v OsValue) Equal(o attr.Value) bool {
	other, ok := o.(OsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.OsId.Equal(other.OsId) {
		return false
	}

	if !v.OsName.Equal(other.OsName) {
		return false
	}

	if !v.OsRelease.Equal(other.OsRelease) {
		return false
	}

	return true
}

func (v OsValue) Type(ctx context.Context) attr.Type {
	return OsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v OsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"os_id":      basetypes.Int64Type{},
		"os_name":    basetypes.StringType{},
		"os_release": basetypes.StringType{},
	}
}
