// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_server_catalog

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ServerCatalogDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"currency": schema.StringAttribute{
				Computed:            true,
				Description:         "Currency of the catalog pricing.",
				MarkdownDescription: "Currency of the catalog pricing.",
			},
			"regions": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"region_active": schema.BoolAttribute{
							Computed:            true,
							Description:         "Whether the region is active.",
							MarkdownDescription: "Whether the region is active.",
						},
						"region_country": schema.StringAttribute{
							Computed:            true,
							Description:         "Region country.",
							MarkdownDescription: "Region country.",
						},
						"region_id": schema.StringAttribute{
							Computed:            true,
							Description:         "Region id.",
							MarkdownDescription: "Region id.",
						},
						"region_name": schema.StringAttribute{
							Computed:            true,
							Description:         "Region name.",
							MarkdownDescription: "Region name.",
						},
						"region_name_short": schema.StringAttribute{
							Computed:            true,
							Description:         "Short region name.",
							MarkdownDescription: "Short region name.",
						},
					},
					CustomType: RegionsType{
						ObjectType: types.ObjectType{
							AttrTypes: RegionsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "Regions servers can be deployed in.",
				MarkdownDescription: "Regions servers can be deployed in.",
			},
			"tiers": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"group_id": schema.Int64Attribute{
							Computed:            true,
							Description:         "Tier (product group) id.",
							MarkdownDescription: "Tier (product group) id.",
						},
						"group_name": schema.StringAttribute{
							Computed:            true,
							Description:         "Tier name.",
							MarkdownDescription: "Tier name.",
						},
						"products": schema.ListNestedAttribute{
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"price_id": schema.Int64Attribute{
										Computed:            true,
										Description:         "Price id for the product, used when deploying.",
										MarkdownDescription: "Price id for the product, used when deploying.",
									},
									"product_hash": schema.StringAttribute{
										Computed:            true,
										Description:         "Product hash.",
										MarkdownDescription: "Product hash.",
									},
									"product_id": schema.Int64Attribute{
										Computed:            true,
										Description:         "Product id, used when deploying.",
										MarkdownDescription: "Product id, used when deploying.",
									},
									"product_name": schema.StringAttribute{
										Computed:            true,
										Description:         "Product name.",
										MarkdownDescription: "Product name.",
									},
									"rate_hourly": schema.Float64Attribute{
										Computed:            true,
										Description:         "Hourly rate.",
										MarkdownDescription: "Hourly rate.",
									},
									"rate_monthly": schema.Int64Attribute{
										Computed:            true,
										Description:         "Monthly cap (the most charged per month).",
										MarkdownDescription: "Monthly cap (the most charged per month).",
									},
									"region_ids": schema.ListAttribute{
										ElementType:         types.Int64Type,
										Computed:            true,
										Description:         "Ids of the regions this product can be deployed in.",
										MarkdownDescription: "Ids of the regions this product can be deployed in.",
									},
									"vm_bw": schema.StringAttribute{
										Computed:            true,
										Description:         "Bandwidth allowance.",
										MarkdownDescription: "Bandwidth allowance.",
									},
									"vm_bw_type": schema.StringAttribute{
										Computed:            true,
										Description:         "Bandwidth allowance type.",
										MarkdownDescription: "Bandwidth allowance type.",
									},
									"vm_cores": schema.StringAttribute{
										Computed:            true,
										Description:         "Number of virtual CPU cores.",
										MarkdownDescription: "Number of virtual CPU cores.",
									},
									"vm_memory": schema.StringAttribute{
										Computed:            true,
										Description:         "Memory, in GB.",
										MarkdownDescription: "Memory, in GB.",
									},
									"vm_storage": schema.StringAttribute{
										Computed:            true,
										Description:         "Storage, in GB.",
										MarkdownDescription: "Storage, in GB.",
									},
								},
								CustomType: ProductsType{
									ObjectType: types.ObjectType{
										AttrTypes: ProductsValue{}.AttributeTypes(ctx),
									},
								},
							},
							Computed:            true,
							Description:         "Products in the tier.",
							MarkdownDescription: "Products in the tier.",
						},
					},
					CustomType: TiersType{
						ObjectType: types.ObjectType{
							AttrTypes: TiersValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "Server product tiers available for hourly deployment.",
				MarkdownDescription: "Server product tiers available for hourly deployment.",
			},
		},
	}
}

type ServerCatalogModel struct {
	Currency types.String `tfsdk:"currency"`
	Regions  types.List   `tfsdk:"regions"`
	Tiers    types.List   `tfsdk:"tiers"`
}

var _ basetypes.ObjectTypable = RegionsType{}

type RegionsType struct {
	basetypes.ObjectType
}

func (t RegionsType) Equal(o attr.Type) bool {
	other, ok := o.(RegionsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t RegionsType) String() string {
	return "RegionsType"
}

func (t RegionsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	regionActiveAttribute, ok := attributes["region_active"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_active is missing from object`)

		return nil, diags
	}

	regionActiveVal, ok := regionActiveAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_active expected to be basetypes.BoolValue, was: %T`, regionActiveAttribute))
	}

	regionCountryAttribute, ok := attributes["region_country"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_country is missing from object`)

		return nil, diags
	}

	regionCountryVal, ok := regionCountryAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_country expected to be basetypes.StringValue, was: %T`, regionCountryAttribute))
	}

	regionIdAttribute, ok := attributes["region_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_id is missing from object`)

		return nil, diags
	}

	regionIdVal, ok := regionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_id expected to be basetypes.StringValue, was: %T`, regionIdAttribute))
	}

	regionNameAttribute, ok := attributes["region_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_name is missing from object`)

		return nil, diags
	}

	regionNameVal, ok := regionNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_name expected to be basetypes.StringValue, was: %T`, regionNameAttribute))
	}

	regionNameShortAttribute, ok := attributes["region_name_short"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_name_short is missing from object`)

		return nil, diags
	}

	regionNameShortVal, ok := regionNameShortAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_name_short expected to be basetypes.StringValue, was: %T`, regionNameShortAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return RegionsValue{
		RegionActive:    regionActiveVal,
		RegionCountry:   regionCountryVal,
		RegionId:        regionIdVal,
		RegionName:      regionNameVal,
		RegionNameShort: regionNameShortVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewRegionsValueNull() RegionsValue {
	return RegionsValue{
		state: attr.ValueStateNull,
	}
}

func NewRegionsValueUnknown() RegionsValue {
	return RegionsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewRegionsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (RegionsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing RegionsValue Attribute Value",
				"While creating a RegionsValue value, a missing attribute value was detected. "+
					"A RegionsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RegionsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid RegionsValue Attribute Type",
				"While creating a RegionsValue value, an invalid attribute value was detected. "+
					"A RegionsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RegionsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("RegionsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra RegionsValue Attribute Value",
				"While creating a RegionsValue value, an extra attribute value was detected. "+
					"A RegionsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra RegionsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewRegionsValueUnknown(), diags
	}

	regionActiveAttribute, ok := attributes["region_active"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_active is missing from object`)

		return NewRegionsValueUnknown(), diags
	}

	regionActiveVal, ok := regionActiveAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_active expected to be basetypes.BoolValue, was: %T`, regionActiveAttribute))
	}

	regionCountryAttribute, ok := attributes["region_country"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_country is missing from object`)

		return NewRegionsValueUnknown(), diags
	}

	regionCountryVal, ok := regionCountryAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_country expected to be basetypes.StringValue, was: %T`, regionCountryAttribute))
	}

	regionIdAttribute, ok := attributes["region_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_id is missing from object`)

		return NewRegionsValueUnknown(), diags
	}

	regionIdVal, ok := regionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_id expected to be basetypes.StringValue, was: %T`, regionIdAttribute))
	}

	regionNameAttribute, ok := attributes["region_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_name is missing from object`)

		return NewRegionsValueUnknown(), diags
	}

	regionNameVal, ok := regionNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_name expected to be basetypes.StringValue, was: %T`, regionNameAttribute))
	}

	regionNameShortAttribute, ok := attributes["region_name_short"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_name_short is missing from object`)

		return NewRegionsValueUnknown(), diags
	}

	regionNameShortVal, ok := regionNameShortAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_name_short expected to be basetypes.StringValue, was: %T`, regionNameShortAttribute))
	}

	if diags.HasError() {
		return NewRegionsValueUnknown(), diags
	}

	return RegionsValue{
		RegionActive:    regionActiveVal,
		RegionCountry:   regionCountryVal,
		RegionId:        regionIdVal,
		RegionName:      regionNameVal,
		RegionNameShort: regionNameShortVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewRegionsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) RegionsValue {
	object, diags := NewRegionsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewRegionsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t RegionsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewRegionsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewRegionsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewRegionsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewRegionsValueMust(RegionsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t RegionsType) ValueType(ctx context.Context) attr.Value {
	return RegionsValue{}
}

var _ basetypes.ObjectValuable = RegionsValue{}

type RegionsValue struct {
	RegionActive    basetypes.BoolValue   `tfsdk:"region_active"`
	RegionCountry   basetypes.StringValue `tfsdk:"region_country"`
	RegionId        basetypes.StringValue `tfsdk:"region_id"`
	RegionName      basetypes.StringValue `tfsdk:"region_name"`
	RegionNameShort basetypes.StringValue `tfsdk:"region_name_short"`
	state           attr.ValueState
}

func (v RegionsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["region_active"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["region_country"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["region_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["region_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["region_name_short"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.RegionActive.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region_active"] = val

		val, err = v.RegionCountry.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region_country"] = val

		val, err = v.RegionId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region_id"] = val

		val, err = v.RegionName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region_name"] = val

		val, err = v.RegionNameShort.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region_name_short"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v RegionsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v RegionsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v RegionsValue) String() string {
	return "RegionsValue"
}

func (v RegionsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"region_active":     basetypes.BoolType{},
		"region_country":    basetypes.StringType{},
		"region_id":         basetypes.StringType{},
		"region_name":       basetypes.StringType{},
		"region_name_short": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"region_active":     v.RegionActive,
			"region_country":    v.RegionCountry,
			"region_id":         v.RegionId,
			"region_name":       v.RegionName,
			"region_name_short": v.RegionNameShort,
		})

	return objVal, diags
}

func (v RegionsValue) Equal(o attr.Value) bool {
	other, ok := o.(RegionsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.RegionActive.Equal(other.RegionActive) {
		return false
	}

	if !v.RegionCountry.Equal(other.RegionCountry) {
		return false
	}

	if !v.RegionId.Equal(other.RegionId) {
		return false
	}

	if !v.RegionName.Equal(other.RegionName) {
		return false
	}

	if !v.RegionNameShort.Equal(other.RegionNameShort) {
		return false
	}

	return true
}

func (v RegionsValue) Type(ctx context.Context) attr.Type {
	return RegionsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v RegionsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"region_active":     basetypes.BoolType{},
		"region_country":    basetypes.StringType{},
		"region_id":         basetypes.StringType{},
		"region_name":       basetypes.StringType{},
		"region_name_short": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = TiersType{}

type TiersType struct {
	basetypes.ObjectType
}

func (t TiersType) Equal(o attr.Type) bool {
	other, ok := o.(TiersType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TiersType) String() string {
	return "TiersType"
}

func (t TiersType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	groupIdAttribute, ok := attributes["group_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`group_id is missing from object`)

		return nil, diags
	}

	groupIdVal, ok := groupIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`group_id expected to be basetypes.Int64Value, was: %T`, groupIdAttribute))
	}

	groupNameAttribute, ok := attributes["group_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`group_name is missing from object`)

		return nil, diags
	}

	groupNameVal, ok := groupNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`group_name expected to be basetypes.StringValue, was: %T`, groupNameAttribute))
	}

	productsAttribute, ok := attributes["products"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`products is missing from object`)

		return nil, diags
	}

	productsVal, ok := productsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`products expected to be basetypes.ListValue, was: %T`, productsAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TiersValue{
		GroupId:   groupIdVal,
		GroupName: groupNameVal,
		Products:  productsVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewTiersValueNull() TiersValue {
	return TiersValue{
		state: attr.ValueStateNull,
	}
}

func NewTiersValueUnknown() TiersValue {
	return TiersValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTiersValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TiersValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TiersValue Attribute Value",
				"While creating a TiersValue value, a missing attribute value was detected. "+
					"A TiersValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TiersValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TiersValue Attribute Type",
				"While creating a TiersValue value, an invalid attribute value was detected. "+
					"A TiersValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TiersValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TiersValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TiersValue Attribute Value",
				"While creating a TiersValue value, an extra attribute value was detected. "+
					"A TiersValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TiersValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTiersValueUnknown(), diags
	}

	groupIdAttribute, ok := attributes["group_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`group_id is missing from object`)

		return NewTiersValueUnknown(), diags
	}

	groupIdVal, ok := groupIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`group_id expected to be basetypes.Int64Value, was: %T`, groupIdAttribute))
	}

	groupNameAttribute, ok := attributes["group_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`group_name is missing from object`)

		return NewTiersValueUnknown(), diags
	}

	groupNameVal, ok := groupNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`group_name expected to be basetypes.StringValue, was: %T`, groupNameAttribute))
	}

	productsAttribute, ok := attributes["products"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`products is missing from object`)

		return NewTiersValueUnknown(), diags
	}

	productsVal, ok := productsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`products expected to be basetypes.ListValue, was: %T`, productsAttribute))
	}

	if diags.HasError() {
		return NewTiersValueUnknown(), diags
	}

	return TiersValue{
		GroupId:   groupIdVal,
		GroupName: groupNameVal,
		Products:  productsVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewTiersValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TiersValue {
	object, diags := NewTiersValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTiersValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TiersType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTiersValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTiersValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTiersValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTiersValueMust(TiersValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TiersType) ValueType(ctx context.Context) attr.Value {
	return TiersValue{}
}

var _ basetypes.ObjectValuable = TiersValue{}

type TiersValue struct {
	GroupId   basetypes.Int64Value  `tfsdk:"group_id"`
	GroupName basetypes.StringValue `tfsdk:"group_name"`
	Products  basetypes.ListValue   `tfsdk:"products"`
	state     attr.ValueState
}

func (v TiersValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["group_id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["group_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["products"] = basetypes.ListType{
		ElemType: ProductsValue{}.Type(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.GroupId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["group_id"] = val

		val, err = v.GroupName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["group_name"] = val

		val, err = v.Products.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["products"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TiersValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TiersValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TiersValue) String() string {
	return "TiersValue"
}

func (v TiersValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	products := types.ListValueMust(
		ProductsType{
			basetypes.ObjectType{
				AttrTypes: ProductsValue{}.AttributeTypes(ctx),
			},
		},
		v.Products.Elements(),
	)

	if v.Products.IsNull() {
		products = types.ListNull(
			ProductsType{
				basetypes.ObjectType{
					AttrTypes: ProductsValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.Products.IsUnknown() {
		products = types.ListUnknown(
			ProductsType{
				basetypes.ObjectType{
					AttrTypes: ProductsValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	attributeTypes := map[string]attr.Type{
		"group_id":   basetypes.Int64Type{},
		"group_name": basetypes.StringType{},
		"products": basetypes.ListType{
			ElemType: ProductsValue{}.Type(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"group_id":   v.GroupId,
			"group_name": v.GroupName,
			"products":   products,
		})

	return objVal, diags
}

func (v TiersValue) Equal(o attr.Value) bool {
	other, ok := o.(TiersValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.GroupId.Equal(other.GroupId) {
		return false
	}

	if !v.GroupName.Equal(other.GroupName) {
		return false
	}

	if !v.Products.Equal(other.Products) {
		return false
	}

	return true
}

func (v TiersValue) Type(ctx context.Context) attr.Type {
	return TiersType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TiersValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"group_id":   basetypes.Int64Type{},
		"group_name": basetypes.StringType{},
		"products": basetypes.ListType{
			ElemType: ProductsValue{}.Type(ctx),
		},
	}
}

var _ basetypes.ObjectTypable = ProductsType{}

type ProductsType struct {
	basetypes.ObjectType
}

func (t ProductsType) Equal(o attr.Type) bool {
	other, ok := o.(ProductsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ProductsType) String() string {
	return "ProductsType"
}

func (t ProductsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	priceIdAttribute, ok := attributes["price_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`price_id is missing from object`)

		return nil, diags
	}

	priceIdVal, ok := priceIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`price_id expected to be basetypes.Int64Value, was: %T`, priceIdAttribute))
	}

	productHashAttribute, ok := attributes["product_hash"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`product_hash is missing from object`)

		return nil, diags
	}

	productHashVal, ok := productHashAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`product_hash expected to be basetypes.StringValue, was: %T`, productHashAttribute))
	}

	productIdAttribute, ok := attributes["product_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`product_id is missing from object`)

		return nil, diags
	}

	productIdVal, ok := productIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`product_id expected to be basetypes.Int64Value, was: %T`, productIdAttribute))
	}

	productNameAttribute, ok := attributes["product_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`product_name is missing from object`)

		return nil, diags
	}

	productNameVal, ok := productNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`product_name expected to be basetypes.StringValue, was: %T`, productNameAttribute))
	}

	rateHourlyAttribute, ok := attributes["rate_hourly"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rate_hourly is missing from object`)

		return nil, diags
	}

	rateHourlyVal, ok := rateHourlyAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rate_hourly expected to be basetypes.Float64Value, was: %T`, rateHourlyAttribute))
	}

	rateMonthlyAttribute, ok := attributes["rate_monthly"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rate_monthly is missing from object`)

		return nil, diags
	}

	rateMonthlyVal, ok := rateMonthlyAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rate_monthly expected to be basetypes.Int64Value, was: %T`, rateMonthlyAttribute))
	}

	regionIdsAttribute, ok := attributes["region_ids"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_ids is missing from object`)

		return nil, diags
	}

	regionIdsVal, ok := regionIdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_ids expected to be basetypes.ListValue, was: %T`, regionIdsAttribute))
	}

	vmBwAttribute, ok := attributes["vm_bw"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vm_bw is missing from object`)

		return nil, diags
	}

	vmBwVal, ok := vmBwAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vm_bw expected to be basetypes.StringValue, was: %T`, vmBwAttribute))
	}

	vmBwTypeAttribute, ok := attributes["vm_bw_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vm_bw_type is missing from object`)

		return nil, diags
	}

	vmBwTypeVal, ok := vmBwTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vm_bw_type expected to be basetypes.StringValue, was: %T`, vmBwTypeAttribute))
	}

	vmCoresAttribute, ok := attributes["vm_cores"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vm_cores is missing from object`)

		return nil, diags
	}

	vmCoresVal, ok := vmCoresAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vm_cores expected to be basetypes.StringValue, was: %T`, vmCoresAttribute))
	}

	vmMemoryAttribute, ok := attributes["vm_memory"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vm_memory is missing from object`)

		return nil, diags
	}

	vmMemoryVal, ok := vmMemoryAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vm_memory expected to be basetypes.StringValue, was: %T`, vmMemoryAttribute))
	}

	vmStorageAttribute, ok := attributes["vm_storage"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vm_storage is missing from object`)

		return nil, diags
	}

	vmStorageVal, ok := vmStorageAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vm_storage expected to be basetypes.StringValue, was: %T`, vmStorageAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ProductsValue{
		PriceId:     priceIdVal,
		ProductHash: productHashVal,
		ProductId:   productIdVal,
		ProductName: productNameVal,
		RateHourly:  rateHourlyVal,
		RateMonthly: rateMonthlyVal,
		RegionIds:   regionIdsVal,
		VmBw:        vmBwVal,
		VmBwType:    vmBwTypeVal,
		VmCores:     vmCoresVal,
		VmMemory:    vmMemoryVal,
		VmStorage:   vmStorageVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewProductsValueNull() ProductsValue {
	return ProductsValue{
		state: attr.ValueStateNull,
	}
}

func NewProductsValueUnknown() ProductsValue {
	return ProductsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewProductsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ProductsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ProductsValue Attribute Value",
				"While creating a ProductsValue value, a missing attribute value was detected. "+
					"A ProductsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ProductsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ProductsValue Attribute Type",
				"While creating a ProductsValue value, an invalid attribute value was detected. "+
					"A ProductsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ProductsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ProductsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ProductsValue Attribute Value",
				"While creating a ProductsValue value, an extra attribute value was detected. "+
					"A ProductsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ProductsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewProductsValueUnknown(), diags
	}

	priceIdAttribute, ok := attributes["price_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`price_id is missing from object`)

		return NewProductsValueUnknown(), diags
	}

	priceIdVal, ok := priceIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`price_id expected to be basetypes.Int64Value, was: %T`, priceIdAttribute))
	}

	productHashAttribute, ok := attributes["product_hash"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`product_hash is missing from object`)

		return NewProductsValueUnknown(), diags
	}

	productHashVal, ok := productHashAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`product_hash expected to be basetypes.StringValue, was: %T`, productHashAttribute))
	}

	productIdAttribute, ok := attributes["product_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`product_id is missing from object`)

		return NewProductsValueUnknown(), diags
	}

	productIdVal, ok := productIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`product_id expected to be basetypes.Int64Value, was: %T`, productIdAttribute))
	}

	productNameAttribute, ok := attributes["product_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`product_name is missing from object`)

		return NewProductsValueUnknown(), diags
	}

	productNameVal, ok := productNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`product_name expected to be basetypes.StringValue, was: %T`, productNameAttribute))
	}

	rateHourlyAttribute, ok := attributes["rate_hourly"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rate_hourly is missing from object`)

		return NewProductsValueUnknown(), diags
	}

	rateHourlyVal, ok := rateHourlyAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rate_hourly expected to be basetypes.Float64Value, was: %T`, rateHourlyAttribute))
	}

	rateMonthlyAttribute, ok := attributes["rate_monthly"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rate_monthly is missing from object`)

		return NewProductsValueUnknown(), diags
	}

	rateMonthlyVal, ok := rateMonthlyAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rate_monthly expected to be basetypes.Int64Value, was: %T`, rateMonthlyAttribute))
	}

	regionIdsAttribute, ok := attributes["region_ids"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_ids is missing from object`)

		return NewProductsValueUnknown(), diags
	}

	regionIdsVal, ok := regionIdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_ids expected to be basetypes.ListValue, was: %T`, regionIdsAttribute))
	}

	vmBwAttribute, ok := attributes["vm_bw"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vm_bw is missing from object`)

		return NewProductsValueUnknown(), diags
	}

	vmBwVal, ok := vmBwAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vm_bw expected to be basetypes.StringValue, was: %T`, vmBwAttribute))
	}

	vmBwTypeAttribute, ok := attributes["vm_bw_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vm_bw_type is missing from object`)

		return NewProductsValueUnknown(), diags
	}

	vmBwTypeVal, ok := vmBwTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vm_bw_type expected to be basetypes.StringValue, was: %T`, vmBwTypeAttribute))
	}

	vmCoresAttribute, ok := attributes["vm_cores"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vm_cores is missing from object`)

		return NewProductsValueUnknown(), diags
	}

	vmCoresVal, ok := vmCoresAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vm_cores expected to be basetypes.StringValue, was: %T`, vmCoresAttribute))
	}

	vmMemoryAttribute, ok := attributes["vm_memory"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vm_memory is missing from object`)

		return NewProductsValueUnknown(), diags
	}

	vmMemoryVal, ok := vmMemoryAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vm_memory expected to be basetypes.StringValue, was: %T`, vmMemoryAttribute))
	}

	vmStorageAttribute, ok := attributes["vm_storage"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vm_storage is missing from object`)

		return NewProductsValueUnknown(), diags
	}

	vmStorageVal, ok := vmStorageAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vm_storage expected to be basetypes.StringValue, was: %T`, vmStorageAttribute))
	}

	if diags.HasError() {
		return NewProductsValueUnknown(), diags
	}

	return ProductsValue{
		PriceId:     priceIdVal,
		ProductHash: productHashVal,
		ProductId:   productIdVal,
		ProductName: productNameVal,
		RateHourly:  rateHourlyVal,
		RateMonthly: rateMonthlyVal,
		RegionIds:   regionIdsVal,
		VmBw:        vmBwVal,
		VmBwType:    vmBwTypeVal,
		VmCores:     vmCoresVal,
		VmMemory:    vmMemoryVal,
		VmStorage:   vmStorageVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewProductsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ProductsValue {
	object, diags := NewProductsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewProductsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ProductsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewProductsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewProductsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewProductsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewProductsValueMust(ProductsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ProductsType) ValueType(ctx context.Context) attr.Value {
	return ProductsValue{}
}

var _ basetypes.ObjectValuable = ProductsValue{}

type ProductsValue struct {
	PriceId     basetypes.Int64Value   `tfsdk:"price_id"`
	ProductHash basetypes.StringValue  `tfsdk:"product_hash"`
	ProductId   basetypes.Int64Value   `tfsdk:"product_id"`
	ProductName basetypes.StringValue  `tfsdk:"product_name"`
	RateHourly  basetypes.Float64Value `tfsdk:"rate_hourly"`
	RateMonthly basetypes.Int64Value   `tfsdk:"rate_monthly"`
	RegionIds   basetypes.ListValue    `tfsdk:"region_ids"`
	VmBw        basetypes.StringValue  `tfsdk:"vm_bw"`
	VmBwType    basetypes.StringValue  `tfsdk:"vm_bw_type"`
	VmCores     basetypes.StringValue  `tfsdk:"vm_cores"`
	VmMemory    basetypes.StringValue  `tfsdk:"vm_memory"`
	VmStorage   basetypes.StringValue  `tfsdk:"vm_storage"`
	state       attr.ValueState
}

func (v ProductsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 12)

	var val tftypes.Value
	var err error

	attrTypes["price_id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["product_hash"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["product_id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["product_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["rate_hourly"] = basetypes.Float64Type{}.TerraformType(ctx)
	attrTypes["rate_monthly"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["region_ids"] = basetypes.ListType{
		ElemType: types.Int64Type,
	}.TerraformType(ctx)
	attrTypes["vm_bw"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["vm_bw_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["vm_cores"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["vm_memory"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["vm_storage"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 12)

		val, err = v.PriceId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["price_id"] = val

		val, err = v.ProductHash.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["product_hash"] = val

		val, err = v.ProductId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["product_id"] = val

		val, err = v.ProductName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["product_name"] = val

		val, err = v.RateHourly.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["rate_hourly"] = val

		val, err = v.RateMonthly.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["rate_monthly"] = val

		val, err = v.RegionIds.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region_ids"] = val

		val, err = v.VmBw.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["vm_bw"] = val

		val, err = v.VmBwType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["vm_bw_type"] = val

		val, err = v.VmCores.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["vm_cores"] = val

		val, err = v.VmMemory.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["vm_memory"] = val

		val, err = v.VmStorage.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["vm_storage"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ProductsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ProductsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ProductsValue) String() string {
	return "ProductsValue"
}

func (v ProductsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var regionIdsVal basetypes.ListValue
	switch {
	case v.RegionIds.IsUnknown():
		regionIdsVal = types.ListUnknown(types.Int64Type)
	case v.RegionIds.IsNull():
		regionIdsVal = types.ListNull(types.Int64Type)
	default:
		var d diag.Diagnostics
		regionIdsVal, d = types.ListValue(types.Int64Type, v.RegionIds.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"price_id":     basetypes.Int64Type{},
			"product_hash": basetypes.StringType{},
			"product_id":   basetypes.Int64Type{},
			"product_name": basetypes.StringType{},
			"rate_hourly":  basetypes.Float64Type{},
			"rate_monthly": basetypes.Int64Type{},
			"region_ids": basetypes.ListType{
				ElemType: types.Int64Type,
			},
			"vm_bw":      basetypes.StringType{},
			"vm_bw_type": basetypes.StringType{},
			"vm_cores":   basetypes.StringType{},
			"vm_memory":  basetypes.StringType{},
			"vm_storage": basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"price_id":     basetypes.Int64Type{},
		"product_hash": basetypes.StringType{},
		"product_id":   basetypes.Int64Type{},
		"product_name": basetypes.StringType{},
		"rate_hourly":  basetypes.Float64Type{},
		"rate_monthly": basetypes.Int64Type{},
		"region_ids": basetypes.ListType{
			ElemType: types.Int64Type,
		},
		"vm_bw":      basetypes.StringType{},
		"vm_bw_type": basetypes.StringType{},
		"vm_cores":   basetypes.StringType{},
		"vm_memory":  basetypes.StringType{},
		"vm_storage": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"price_id":     v.PriceId,
			"product_hash": v.ProductHash,
			"product_id":   v.ProductId,
			"product_name": v.ProductName,
			"rate_hourly":  v.RateHourly,
			"rate_monthly": v.RateMonthly,
			"region_ids":   regionIdsVal,
			"vm_bw":        v.VmBw,
			"vm_bw_type":   v.VmBwType,
			"vm_cores":     v.VmCores,
			"vm_memory":    v.VmMemory,
			"vm_storage":   v.VmStorage,
		})

	return objVal, diags
}

func (v ProductsValue) Equal(o attr.Value) bool {
	other, ok := o.(ProductsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.PriceId.Equal(other.PriceId) {
		return false
	}

	if !v.ProductHash.Equal(other.ProductHash) {
		return false
	}

	if !v.ProductId.Equal(other.ProductId) {
		return false
	}

	if !v.ProductName.Equal(other.ProductName) {
		return false
	}

	if !v.RateHourly.Equal(other.RateHourly) {
		return false
	}

	if !v.RateMonthly.Equal(other.RateMonthly) {
		return false
	}

	if !v.RegionIds.Equal(other.RegionIds) {
		return false
	}

	if !v.VmBw.Equal(other.VmBw) {
		return false
	}

	if !v.VmBwType.Equal(other.VmBwType) {
		return false
	}

	if !v.VmCores.Equal(other.VmCores) {
		return false
	}

	if !v.VmMemory.Equal(other.VmMemory) {
		return false
	}

	if !v.VmStorage.Equal(other.VmStorage) {
		return false
	}

	return true
}

func (v ProductsValue) Type(ctx context.Context) attr.Type {
	return ProductsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ProductsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"price_id":     basetypes.Int64Type{},
		"product_hash": basetypes.StringType{},
		"product_id":   basetypes.Int64Type{},
		"product_name": basetypes.StringType{},
		"rate_hourly":  basetypes.Float64Type{},
		"rate_monthly": basetypes.Int64Type{},
		"region_ids": basetypes.ListType{
			ElemType: types.Int64Type,
		},
		"vm_bw":      basetypes.StringType{},
		"vm_bw_type": basetypes.StringType{},
		"vm_cores":   basetypes.StringType{},
		"vm_memory":  basetypes.StringType{},
		"vm_storage": basetypes.StringType{},
	}
}
