// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_dns_zones

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func DnsZonesDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"zones": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"external_dns": schema.BoolAttribute{
							Computed:            true,
							Description:         "Whether the zone is served by external nameservers.",
							MarkdownDescription: "Whether the zone is served by external nameservers.",
						},
						"zone_active": schema.BoolAttribute{
							Computed:            true,
							Description:         "Whether the zone is active.",
							MarkdownDescription: "Whether the zone is active.",
						},
						"zone_id": schema.StringAttribute{
							Computed:            true,
							Description:         "Zone id.",
							MarkdownDescription: "Zone id.",
						},
						"zone_name": schema.StringAttribute{
							Computed:            true,
							Description:         "Domain name.",
							MarkdownDescription: "Domain name.",
						},
						"zone_protected": schema.BoolAttribute{
							Computed:            true,
							Description:         "Whether the zone is protected against deletion.",
							MarkdownDescription: "Whether the zone is protected against deletion.",
						},
						"zone_type": schema.StringAttribute{
							Computed:            true,
							Description:         "Zone type (NATIVE, MASTER, or SLAVE).",
							MarkdownDescription: "Zone type (NATIVE, MASTER, or SLAVE).",
						},
					},
					CustomType: ZonesType{
						ObjectType: types.ObjectType{
							AttrTypes: ZonesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "DNS zones on the account.",
				MarkdownDescription: "DNS zones on the account.",
			},
		},
	}
}

type DnsZonesModel struct {
	Zones types.List `tfsdk:"zones"`
}

var _ basetypes.ObjectTypable = ZonesType{}

type ZonesType struct {
	basetypes.ObjectType
}

func (t ZonesType) Equal(o attr.Type) bool {
	other, ok := o.(ZonesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ZonesType) String() string {
	return "ZonesType"
}

func (t ZonesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	externalDnsAttribute, ok := attributes["external_dns"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`external_dns is missing from object`)

		return nil, diags
	}

	externalDnsVal, ok := externalDnsAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`external_dns expected to be basetypes.BoolValue, was: %T`, externalDnsAttribute))
	}

	zoneActiveAttribute, ok := attributes["zone_active"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zone_active is missing from object`)

		return nil, diags
	}

	zoneActiveVal, ok := zoneActiveAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zone_active expected to be basetypes.BoolValue, was: %T`, zoneActiveAttribute))
	}

	zoneIdAttribute, ok := attributes["zone_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zone_id is missing from object`)

		return nil, diags
	}

	zoneIdVal, ok := zoneIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zone_id expected to be basetypes.StringValue, was: %T`, zoneIdAttribute))
	}

	zoneNameAttribute, ok := attributes["zone_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zone_name is missing from object`)

		return nil, diags
	}

	zoneNameVal, ok := zoneNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zone_name expected to be basetypes.StringValue, was: %T`, zoneNameAttribute))
	}

	zoneProtectedAttribute, ok := attributes["zone_protected"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zone_protected is missing from object`)

		return nil, diags
	}

	zoneProtectedVal, ok := zoneProtectedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zone_protected expected to be basetypes.BoolValue, was: %T`, zoneProtectedAttribute))
	}

	zoneTypeAttribute, ok := attributes["zone_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zone_type is missing from object`)

		return nil, diags
	}

	zoneTypeVal, ok := zoneTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zone_type expected to be basetypes.StringValue, was: %T`, zoneTypeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ZonesValue{
		ExternalDns:   externalDnsVal,
		ZoneActive:    zoneActiveVal,
		ZoneId:        zoneIdVal,
		ZoneName:      zoneNameVal,
		ZoneProtected: zoneProtectedVal,
		ZoneType:      zoneTypeVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewZonesValueNull() ZonesValue {
	return ZonesValue{
		state: attr.ValueStateNull,
	}
}

func NewZonesValueUnknown() ZonesValue {
	return ZonesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewZonesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ZonesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ZonesValue Attribute Value",
				"While creating a ZonesValue value, a missing attribute value was detected. "+
					"A ZonesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ZonesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ZonesValue Attribute Type",
				"While creating a ZonesValue value, an invalid attribute value was detected. "+
					"A ZonesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ZonesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ZonesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ZonesValue Attribute Value",
				"While creating a ZonesValue value, an extra attribute value was detected. "+
					"A ZonesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ZonesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewZonesValueUnknown(), diags
	}

	externalDnsAttribute, ok := attributes["external_dns"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`external_dns is missing from object`)

		return NewZonesValueUnknown(), diags
	}

	externalDnsVal, ok := externalDnsAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`external_dns expected to be basetypes.BoolValue, was: %T`, externalDnsAttribute))
	}

	zoneActiveAttribute, ok := attributes["zone_active"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zone_active is missing from object`)

		return NewZonesValueUnknown(), diags
	}

	zoneActiveVal, ok := zoneActiveAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zone_active expected to be basetypes.BoolValue, was: %T`, zoneActiveAttribute))
	}

	zoneIdAttribute, ok := attributes["zone_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zone_id is missing from object`)

		return NewZonesValueUnknown(), diags
	}

	zoneIdVal, ok := zoneIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zone_id expected to be basetypes.StringValue, was: %T`, zoneIdAttribute))
	}

	zoneNameAttribute, ok := attributes["zone_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zone_name is missing from object`)

		return NewZonesValueUnknown(), diags
	}

	zoneNameVal, ok := zoneNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zone_name expected to be basetypes.StringValue, was: %T`, zoneNameAttribute))
	}

	zoneProtectedAttribute, ok := attributes["zone_protected"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zone_protected is missing from object`)

		return NewZonesValueUnknown(), diags
	}

	zoneProtectedVal, ok := zoneProtectedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zone_protected expected to be basetypes.BoolValue, was: %T`, zoneProtectedAttribute))
	}

	zoneTypeAttribute, ok := attributes["zone_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zone_type is missing from object`)

		return NewZonesValueUnknown(), diags
	}

	zoneTypeVal, ok := zoneTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zone_type expected to be basetypes.StringValue, was: %T`, zoneTypeAttribute))
	}

	if diags.HasError() {
		return NewZonesValueUnknown(), diags
	}

	return ZonesValue{
		ExternalDns:   externalDnsVal,
		ZoneActive:    zoneActiveVal,
		ZoneId:        zoneIdVal,
		ZoneName:      zoneNameVal,
		ZoneProtected: zoneProtectedVal,
		ZoneType:      zoneTypeVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewZonesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ZonesValue {
	object, diags := NewZonesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewZonesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ZonesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewZonesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewZonesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewZonesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewZonesValueMust(ZonesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ZonesType) ValueType(ctx context.Context) attr.Value {
	return ZonesValue{}
}

var _ basetypes.ObjectValuable = ZonesValue{}

type ZonesValue struct {
	ExternalDns   basetypes.BoolValue   `tfsdk:"external_dns"`
	ZoneActive    basetypes.BoolValue   `tfsdk:"zone_active"`
	ZoneId        basetypes.StringValue `tfsdk:"zone_id"`
	ZoneName      basetypes.StringValue `tfsdk:"zone_name"`
	ZoneProtected basetypes.BoolValue   `tfsdk:"zone_protected"`
	ZoneType      basetypes.StringValue `tfsdk:"zone_type"`
	state         attr.ValueState
}

func (v ZonesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["external_dns"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["zone_active"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["zone_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["zone_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["zone_protected"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["zone_type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.ExternalDns.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["external_dns"] = val

		val, err = v.ZoneActive.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["zone_active"] = val

		val, err = v.ZoneId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["zone_id"] = val

		val, err = v.ZoneName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["zone_name"] = val

		val, err = v.ZoneProtected.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["zone_protected"] = val

		val, err = v.ZoneType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["zone_type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ZonesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ZonesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ZonesValue) String() string {
	return "ZonesValue"
}

func (v ZonesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"external_dns":   basetypes.BoolType{},
		"zone_active":    basetypes.BoolType{},
		"zone_id":        basetypes.StringType{},
		"zone_name":      basetypes.StringType{},
		"zone_protected": basetypes.BoolType{},
		"zone_type":      basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"external_dns":   v.ExternalDns,
			"zone_active":    v.ZoneActive,
			"zone_id":        v.ZoneId,
			"zone_name":      v.ZoneName,
			"zone_protected": v.ZoneProtected,
			"zone_type":      v.ZoneType,
		})

	return objVal, diags
}

func (v ZonesValue) Equal(o attr.Value) bool {
	other, ok := o.(ZonesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ExternalDns.Equal(other.ExternalDns) {
		return false
	}

	if !v.ZoneActive.Equal(other.ZoneActive) {
		return false
	}

	if !v.ZoneId.Equal(other.ZoneId) {
		return false
	}

	if !v.ZoneName.Equal(other.ZoneName) {
		return false
	}

	if !v.ZoneProtected.Equal(other.ZoneProtected) {
		return false
	}

	if !v.ZoneType.Equal(other.ZoneType) {
		return false
	}

	return true
}

func (v ZonesValue) Type(ctx context.Context) attr.Type {
	return ZonesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ZonesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"external_dns":   basetypes.BoolType{},
		"zone_active":    basetypes.BoolType{},
		"zone_id":        basetypes.StringType{},
		"zone_name":      basetypes.StringType{},
		"zone_protected": basetypes.BoolType{},
		"zone_type":      basetypes.StringType{},
	}
}
